# Generated by Django 6.0.4 on 2026-06-03 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_projectlog_projectlogentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottleneck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ISSUE', 'Issue'), ('CONCERN', 'Concern'), ('RISK', 'Risk'), ('ACTION', 'Action')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('target_date', models.DateField(blank=True, db_index=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bottlenecks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bottlenecks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bottlenecks', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bottlenecks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bottleneck Item',
                'verbose_name_plural': 'Bottleneck Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'type'], name='bottlenecks_project_d84265_idx'), models.Index(fields=['project', 'status'], name='bottlenecks_project_ce46e7_idx'), models.Index(fields=['project', 'priority'], name='bottlenecks_project_f4921e_idx'), models.Index(fields=['project', 'target_date'], name='bottlenecks_project_6223c1_idx')],
            },
        ),
    ]
