# Generated by Django 6.0 on 2026-07-31 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottlenecks', '0002_bottleneck_client_id'),
        ('projects', '0015_optimize_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bottleneck',
            index=models.Index(fields=['project', '-created_at'], name='bn_proj_created_idx'),
        ),
    ]
