# Generated by Django 5.2.13 on 2026-05-27 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectQualityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_index=True, help_text='Unique project name for this quality status record', max_length=255, unique=True)),
                ('totalTestsConducted', models.PositiveIntegerField(default=0, help_text='Total number of quality tests conducted')),
                ('totalTestsPassed', models.PositiveIntegerField(default=0, help_text='Total number of quality tests passed (cannot exceed totalTestsConducted)')),
                ('variance', models.IntegerField(default=0, editable=False, help_text='Auto-calculated: totalTestsConducted - totalTestsPassed. Represents the number of failed / pending tests.')),
                ('performancePercentage', models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: (totalTestsPassed / totalTestsConducted) * 100. 0.0 when totalTestsConducted = 0.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Project Quality Status',
                'verbose_name_plural': 'Project Quality Status Records',
                'ordering': ['projectName'],
                'indexes': [models.Index(fields=['projectName'], name='pqs_project_name_idx')],
            },
        ),
    ]
