# Generated by Django 5.2.13 on 2026-06-01

from datetime import date

from django.db import migrations, models


def migrate_legacy_quality_records(apps, schema_editor):
    """Map legacy cumulative fields to monthly structure."""
    ProjectQualityStatus = apps.get_model("project_quality_status", "ProjectQualityStatus")
    today = date.today()

    for record in ProjectQualityStatus.objects.all():
        if record.created_at:
            record.month = record.created_at.month
            record.year = record.created_at.year
        else:
            record.month = today.month
            record.year = today.year

        conducted = record.totalTestsConducted or 0
        passed = record.totalTestsPassed or 0
        failed = max(conducted - passed, 0)

        record.tests_conducted = conducted
        record.tests_passed = passed
        record.tests_failed = failed
        record.tests_required = conducted
        record.save(
            update_fields=[
                "month",
                "year",
                "tests_required",
                "tests_conducted",
                "tests_passed",
                "tests_failed",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("project_quality_status", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectqualitystatus",
            name="month",
            field=models.PositiveSmallIntegerField(db_index=True, default=1, help_text="Month number (1–12)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectqualitystatus",
            name="year",
            field=models.PositiveSmallIntegerField(db_index=True, default=2026, help_text="Year (e.g. 2026)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectqualitystatus",
            name="tests_required",
            field=models.PositiveIntegerField(default=0, help_text="Number of quality tests required for the month"),
        ),
        migrations.AddField(
            model_name="projectqualitystatus",
            name="tests_conducted",
            field=models.PositiveIntegerField(default=0, help_text="Number of quality tests conducted"),
        ),
        migrations.AddField(
            model_name="projectqualitystatus",
            name="tests_passed",
            field=models.PositiveIntegerField(default=0, help_text="Number of tests passed"),
        ),
        migrations.AddField(
            model_name="projectqualitystatus",
            name="tests_failed",
            field=models.PositiveIntegerField(default=0, help_text="Number of tests failed"),
        ),
        migrations.RunPython(migrate_legacy_quality_records, migrations.RunPython.noop),
        migrations.RemoveField(model_name="projectqualitystatus", name="totalTestsConducted"),
        migrations.RemoveField(model_name="projectqualitystatus", name="totalTestsPassed"),
        migrations.RemoveField(model_name="projectqualitystatus", name="variance"),
        migrations.RemoveField(model_name="projectqualitystatus", name="performancePercentage"),
        migrations.AlterField(
            model_name="projectqualitystatus",
            name="projectName",
            field=models.CharField(
                db_index=True,
                help_text="Project name for this quality status record",
                max_length=255,
            ),
        ),
        migrations.AlterModelOptions(
            name="projectqualitystatus",
            options={
                "ordering": ["projectName", "year", "month"],
                "verbose_name": "Project Quality Status",
                "verbose_name_plural": "Project Quality Status Records",
            },
        ),
        migrations.AlterUniqueTogether(
            name="projectqualitystatus",
            unique_together={("projectName", "month", "year")},
        ),
        migrations.RemoveIndex(
            model_name="projectqualitystatus",
            name="pqs_project_name_idx",
        ),
        migrations.AddIndex(
            model_name="projectqualitystatus",
            index=models.Index(
                fields=["projectName", "year", "month"],
                name="pqs_proj_year_month_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectqualitystatus",
            index=models.Index(fields=["year", "month"], name="pqs_year_month_idx"),
        ),
    ]
