# Generated by Django 6.0.4 on 2026-06-12 09:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_quality_status', '0002_monthly_quality_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFrequencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, db_index=True, default='', help_text='Blank = global template; otherwise project-specific rule', max_length=255)),
                ('item_description', models.CharField(db_index=True, max_length=500)),
                ('type_of_test', models.CharField(db_index=True, max_length=255)),
                ('unit', models.CharField(default='', max_length=50)),
                ('frequency_value', models.DecimalField(decimal_places=4, default=1, help_text="Tests numerator (e.g. 1 in '1 test / 30 cum')", max_digits=12)),
                ('frequency_quantity', models.DecimalField(decimal_places=4, default=1, help_text="Quantity denominator (e.g. 30 in '1 test / 30 cum')", max_digits=12)),
                ('frequency_display', models.CharField(blank=True, default='', help_text="Display label e.g. '1 Test / 30 Cum'", max_length=255)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Frequency Master',
                'verbose_name_plural': 'Test Frequency Masters',
                'ordering': ['item_description', 'type_of_test'],
                'indexes': [models.Index(fields=['projectName', 'item_description'], name='freq_master_proj_item_idx')],
            },
        ),
        migrations.CreateModel(
            name='FrequencyChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_index=True, max_length=255)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('sr_no', models.PositiveIntegerField()),
                ('item_description', models.CharField(max_length=500)),
                ('type_of_test', models.CharField(db_index=True, max_length=255)),
                ('unit', models.CharField(default='', max_length=50)),
                ('activity_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('contractor_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('frequency_value', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('frequency_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('frequency_display', models.CharField(blank=True, default='', max_length=255)),
                ('qty_previous_bill', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('qty_this_bill', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('field_lab_previous_bill', models.PositiveIntegerField(default=0)),
                ('field_lab_this_bill', models.PositiveIntegerField(default=0)),
                ('third_party_previous_bill', models.PositiveIntegerField(default=0)),
                ('third_party_this_bill', models.PositiveIntegerField(default=0)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_entries', to='project_quality_status.testfrequencymaster')),
            ],
            options={
                'verbose_name': 'Frequency Chart Entry',
                'verbose_name_plural': 'Frequency Chart Entries',
                'ordering': ['projectName', 'year', 'month', 'sr_no'],
                'indexes': [models.Index(fields=['projectName', 'year', 'month'], name='freq_chart_proj_period_idx'), models.Index(fields=['projectName', 'type_of_test'], name='freq_chart_proj_test_idx')],
                'constraints': [models.UniqueConstraint(fields=('projectName', 'year', 'month', 'sr_no'), name='freq_chart_unique_proj_period_sr')],
            },
        ),
    ]
