# Generated by Django 6.0 on 2026-07-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_quality_status', '0003_frequency_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencychartentry',
            name='conducted_tests',
            field=models.PositiveIntegerField(default=0, help_text='Manually entered conducted tests'),
        ),
        migrations.AddField(
            model_name='frequencychartentry',
            name='passed_tests',
            field=models.PositiveIntegerField(default=0, help_text='Manually entered passed tests'),
        ),
        migrations.AddField(
            model_name='frequencychartentry',
            name='required_tests',
            field=models.PositiveIntegerField(default=0, help_text='Manually entered required tests. Future: may be auto-filled from Frequency Master.'),
        ),
    ]
