# Generated by Django 5.2.13 on 2026-05-27 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedEarnedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_index=True, help_text='Unique project name for this Planned vs Earned Value record', max_length=255, unique=True)),
                ('plannedValue', models.DecimalField(decimal_places=4, default=0, help_text='Planned Value (PV) — budgeted cost of work scheduled', max_digits=20)),
                ('earnedValue', models.DecimalField(decimal_places=4, default=0, help_text='Earned Value (EV) — budgeted cost of work performed. Can be greater than plannedValue (ahead of schedule).', max_digits=20)),
                ('variance', models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Auto-calculated: earnedValue - plannedValue. Positive = ahead of schedule. Negative = behind schedule.', max_digits=20)),
                ('variancePercentage', models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: (variance / plannedValue) * 100. 0.0 when plannedValue = 0.')),
                ('performancePercentage', models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: (earnedValue / plannedValue) * 100. Represents Schedule Performance Index as a percentage. 0.0 when plannedValue = 0.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Planned vs Earned Value',
                'verbose_name_plural': 'Planned vs Earned Value Records',
                'ordering': ['projectName'],
                'indexes': [models.Index(fields=['projectName'], name='pev_project_name_idx')],
            },
        ),
    ]
