# Generated by Django 5.2.13 on 2026-06-01

from datetime import date

from django.db import migrations, models


def populate_month_year_from_created_at(apps, schema_editor):
    """Set month/year on existing records from created_at (fallback: today)."""
    PlannedEarnedValue = apps.get_model("planned_earned_value", "PlannedEarnedValue")
    today = date.today()
    for record in PlannedEarnedValue.objects.all():
        if record.created_at:
            record.month = record.created_at.month
            record.year = record.created_at.year
        else:
            record.month = today.month
            record.year = today.year
        record.save(update_fields=["month", "year"])


class Migration(migrations.Migration):

    dependencies = [
        ("planned_earned_value", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedearnedvalue",
            name="value_type",
            field=models.CharField(
                choices=[("SCL", "SCL"), ("CONTRACTOR", "CONTRACTOR")],
                db_index=True,
                default="SCL",
                help_text="SCL or CONTRACTOR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plannedearnedvalue",
            name="month",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Month number (1–12)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plannedearnedvalue",
            name="year",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=2026,
                help_text="Year (e.g. 2026)",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_month_year_from_created_at,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="plannedearnedvalue",
            name="projectName",
            field=models.CharField(
                db_index=True,
                help_text="Project name for this Planned vs Earned Value record",
                max_length=255,
            ),
        ),
        migrations.AlterModelOptions(
            name="plannedearnedvalue",
            options={
                "ordering": ["projectName", "year", "month", "value_type"],
                "verbose_name": "Planned vs Earned Value",
                "verbose_name_plural": "Planned vs Earned Value Records",
            },
        ),
        migrations.AlterUniqueTogether(
            name="plannedearnedvalue",
            unique_together={("projectName", "value_type", "month", "year")},
        ),
        migrations.RemoveIndex(
            model_name="plannedearnedvalue",
            name="pev_project_name_idx",
        ),
        migrations.AddIndex(
            model_name="plannedearnedvalue",
            index=models.Index(
                fields=["projectName", "value_type", "year", "month"],
                name="pev_proj_type_year_month_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plannedearnedvalue",
            index=models.Index(fields=["year", "month"], name="pev_year_month_idx"),
        ),
    ]
