# Generated by Django 6.0.4 on 2026-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planned_earned_value', '0002_scl_contractor_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedearnedvalue',
            name='performancePercentage',
            field=models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: (earnedValue / plannedValue) * 100'),
        ),
        migrations.AlterField(
            model_name='plannedearnedvalue',
            name='variance',
            field=models.DecimalField(decimal_places=4, default=0, editable=False, help_text='Auto-calculated: earnedValue - plannedValue', max_digits=20),
        ),
        migrations.AlterField(
            model_name='plannedearnedvalue',
            name='variancePercentage',
            field=models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: (variance / plannedValue) * 100'),
        ),
    ]
