# Generated by Django 6.0.4 on 2026-07-10 05:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planned_earned_value', '0004_refactor_planned_vs_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedearnedvalue',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='plannedearnedvalue',
            name='month',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='plannedearnedvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plannedearnedvalue',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
    ]
