# Generated by Django 5.2.13 on 2026-06-01 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_projectlog_projectlogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(choices=[('SCL', 'SCL'), ('CONTRACTOR', 'CONTRACTOR')], db_index=True, help_text='SCL or CONTRACTOR', max_length=20)),
                ('project_start', models.DateField(help_text='Project start date')),
                ('contract_finish', models.DateField(help_text='Contractual finish date')),
                ('forecast_finish', models.DateField(help_text='Forecasted finish date')),
                ('eot_date', models.DateField(help_text='Extension of Time (EOT) date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('project', models.ForeignKey(help_text='Project this date record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='project_dates', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Dates',
                'verbose_name_plural': 'Project Dates',
                'ordering': ['project__name', 'date_type'],
                'indexes': [models.Index(fields=['project', 'date_type'], name='pd_project_date_type_idx'), models.Index(fields=['date_type'], name='pd_date_type_idx')],
                'unique_together': {('project', 'date_type')},
            },
        ),
    ]
