# Generated by Django 5.2.13 on 2026-07-01 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
        ('project_dates', '0005_projectdates_multi_contractor'),
        ('projects', '0012_project_site_engineer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectbgstatus',
            options={'verbose_name': 'Project BG Status', 'verbose_name_plural': 'Project BG Status Records'},
        ),
        migrations.AlterModelOptions(
            name='projectdates',
            options={'ordering': ['project__name', 'date_type', 'contractor_name'], 'verbose_name': 'Project Dates', 'verbose_name_plural': 'Project Dates'},
        ),
        migrations.RemoveConstraint(
            model_name='projectdates',
            name='pd_unique_contractor_name_per_project',
        ),
        migrations.AddField(
            model_name='projectdates',
            name='contractor',
            field=models.ForeignKey(blank=True, help_text='Contractor Master reference (required for CONTRACTOR)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_dates', to='contractors.contractor'),
        ),
        migrations.AlterField(
            model_name='bgstatus',
            name='bg_type',
            field=models.CharField(choices=[('CONTRACTOR', 'Contractor'), ('SCL', 'SCL')], db_index=True, help_text='Contract type for this bank guarantee', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdates',
            name='contractor_name',
            field=models.CharField(blank=True, db_index=True, help_text='Contractor display name (denormalized from Contractor Master)', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='projectdates',
            constraint=models.UniqueConstraint(condition=models.Q(('date_type', 'CONTRACTOR')), fields=('project', 'contractor'), name='pd_unique_contractor_per_project'),
        ),
    ]
