# Generated by Django 6.0 on 2026-07-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_dates', '0006_alter_projectbgstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgstatus',
            name='bg_name',
            field=models.CharField(blank=True, default='', help_text='Display name for this bank guarantee (optional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='bgstatus',
            name='due_date',
            field=models.DateField(blank=True, help_text='Bank guarantee due date (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='projectdates',
            name='eot_date',
            field=models.DateField(blank=True, help_text='Extension of Time (EOT) date (optional)', null=True),
        ),
    ]
