# Generated by Django 6.0 on 2026-08-05 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_dates', '0007_make_eot_and_bg_fields_optional'),
        ('projects', '0016_project_completion_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eot_number', models.PositiveIntegerField(help_text='Sequential EOT number within the project (1, 2, 3…)')),
                ('extension_days', models.PositiveIntegerField(help_text='Approved/requested extension in calendar days (must be > 0)')),
                ('original_completion_date', models.DateField(help_text='Completion date before this EOT')),
                ('revised_completion_date', models.DateField(help_text='Completion date after applying this EOT')),
                ('approval_date', models.DateField(blank=True, help_text='Date the EOT was approved (required when status=approved)', null=True)),
                ('reason', models.TextField(help_text='Primary reason for the extension')),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('supporting_document', models.FileField(blank=True, help_text='Optional supporting document', null=True, upload_to='eot_documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False = soft-deleted; excluded from latest completion calculations')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_eots', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this EOT belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='eots', to='projects.project')),
                ('project_dates', models.ForeignKey(blank=True, help_text='Optional link to SCL/Contractor schedule row', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eot_records', to='project_dates.projectdates')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_eots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project EOT',
                'verbose_name_plural': 'Project EOTs',
                'ordering': ['project_id', 'eot_number'],
                'indexes': [models.Index(fields=['project', 'status', 'is_active'], name='eot_proj_status_active_idx'), models.Index(fields=['project', '-eot_number'], name='eot_proj_number_desc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'eot_number'), name='eot_unique_active_number_per_project'), models.CheckConstraint(condition=models.Q(('extension_days__gt', 0)), name='eot_extension_days_positive')],
            },
        ),
    ]
