# Generated by Django 6.0 on 2026-02-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_client_name_project_commencement_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='has_bar_gantt_chart',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_dpr_format',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_mis',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_mpr_format',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_reminder_alerts',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_wpr_format',
        ),
        migrations.AddField(
            model_name='project',
            name='documentation_file',
            field=models.FileField(blank=True, null=True, upload_to='project_docs/'),
        ),
    ]
