# Generated by Django 6.0.2 on 2026-03-18 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('earned_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bcwp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ac', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('actual_billed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('original_contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('approved_vo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('revised_contract_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pending_vo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('gross_billed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_billed', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_collected', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_due', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('contract_finish_date', models.DateField(blank=True, null=True)),
                ('forecast_finish_date', models.DateField(blank=True, null=True)),
                ('delay_days', models.IntegerField(blank=True, null=True)),
                ('fatalities', models.IntegerField(default=0)),
                ('significant', models.IntegerField(default=0)),
                ('major', models.IntegerField(default=0)),
                ('minor', models.IntegerField(default=0)),
                ('near_miss', models.IntegerField(default=0)),
                ('total_manhours', models.BigIntegerField(blank=True, null=True)),
                ('loss_of_manhours', models.BigIntegerField(blank=True, null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_data', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Dashboard Data',
                'verbose_name_plural': 'Project Dashboard Data',
            },
        ),
    ]
