# Generated by Django 6.0.2 on 2026-03-20 11:27

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_billing_site_engineer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved_vo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Approved Variation Order', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to this project', related_name='init_assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='bac',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Budget at Completion', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_finish',
            field=models.DateField(blank=True, help_text='Contractual finish date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delay_days',
            field=models.IntegerField(default=0, help_text='Auto-calculated: Days between forecast and contract finish'),
        ),
        migrations.AddField(
            model_name='project',
            name='forecast_finish',
            field=models.DateField(blank=True, help_text='Forecasted finish date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='original_contract_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original contract value', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='pending_vo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pending Variation Order', max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='project_start',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='revised_contract_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-calculated: Original Contract Value + Approved VO', max_digits=15),
        ),
        migrations.AddField(
            model_name='project',
            name='working_days_per_month',
            field=models.IntegerField(default=26, help_text='Working days per month', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='project',
            name='working_hours_per_day',
            field=models.FloatField(default=8.0, help_text='Working hours per day', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
