# Generated by Django 5.2.13 on 2026-05-26 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_options_alter_project_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_log', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_project_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Log',
                'verbose_name_plural': 'Project Logs',
            },
        ),
        migrations.CreateModel(
            name='ProjectLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('issue_concern', 'Issue / Concern'), ('risk_action', 'Risk / Action')], db_index=True, max_length=20)),
                ('left_text', models.TextField(blank=True, help_text='Issue or Risk')),
                ('right_text', models.TextField(blank=True, help_text='Concern or Action')),
                ('row_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('project_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='projects.projectlog')),
            ],
            options={
                'verbose_name': 'Project Log Entry',
                'verbose_name_plural': 'Project Log Entries',
                'ordering': ['entry_type', 'row_order'],
            },
        ),
    ]
