# Generated by Django 6.0.4 on 2026-07-20 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_site_engineer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hse_site_engineer',
            field=models.ForeignKey(blank=True, help_text='Health, Safety & Environment Site Engineer for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hse_engineer_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
