# Generated by Django 6.0 on 2026-07-20 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_hse_site_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text='If status=merged, the surviving project this record was merged into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('merged', 'Merged into another project')], db_index=True, default='planning', max_length=20),
        ),
    ]
