# Generated by Django 6.0 on 2026-07-31 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_merged_into'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-updated_at'], name='project_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['client_name'], name='project_client_name_idx'),
        ),
        migrations.AddIndex(
            model_name='projectlogentry',
            index=models.Index(fields=['project_log', 'entry_type', 'row_order'], name='plog_entry_type_order_idx'),
        ),
    ]
