# Generated by Django 6.0 on 2026-07-31 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_optimize_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the project was marked completed', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completed_by',
            field=models.ForeignKey(blank=True, help_text='User who marked the project completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_notes',
            field=models.TextField(blank=True, default='', help_text='Optional remarks captured at completion'),
        ),
    ]
