# Generated by Django 6.0 on 2026-08-06 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0018_billing_status_db_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('project', 'Project'), ('dpr', 'DPR'), ('eot', 'EOT'), ('contract_value', 'Contract Value'), ('site_image', 'Site Image'), ('assignment', 'Assignment')], db_index=True, max_length=40)),
                ('entity_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('project_name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('billing_completed', 'Billing Completed'), ('uploaded', 'Uploaded'), ('assigned', 'Assigned')], db_index=True, max_length=40)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_audit_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='biz_audit_entity_created_idx'), models.Index(fields=['project', '-created_at'], name='biz_audit_project_created_idx')],
            },
        ),
    ]
