# Generated by Django 6.0 on 2026-08-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_business_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessauditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('billing_completed', 'Billing Completed'), ('uploaded', 'Uploaded'), ('assigned', 'Assigned'), ('failed', 'Failed')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='businessauditlog',
            name='entity_type',
            field=models.CharField(choices=[('project', 'Project'), ('dpr', 'DPR'), ('eot', 'EOT'), ('contract_value', 'Contract Value'), ('site_image', 'Site Image'), ('assignment', 'Assignment'), ('tutorial_video', 'Tutorial Video'), ('mpr', 'MPR')], db_index=True, max_length=40),
        ),
    ]
