# Generated by Django 6.0 on 2026-07-21 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0014_project_merged_into'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(db_index=True, max_length=255)),
                ('issue_description', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], db_index=True, default='Open', max_length=16)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_index=True, default='Medium', max_length=16)),
                ('attachment_url', models.URLField(blank=True, default='', max_length=1000)),
                ('attachment_name', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_size', models.PositiveBigIntegerField(default=0)),
                ('attachment_type', models.CharField(blank=True, default='', max_length=120)),
                ('attachment_key', models.CharField(blank=True, default='', max_length=700)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_feedback', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_items', to='projects.project')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Feedback',
                'verbose_name_plural': 'Project Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('attachment_updated', 'Attachment Updated'), ('deleted', 'Deleted')], db_index=True, max_length=32)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_audit_logs', to='projects.project')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='feedback_management.projectfeedback')),
            ],
            options={
                'verbose_name': 'Feedback Audit Log',
                'verbose_name_plural': 'Feedback Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectfeedback',
            index=models.Index(fields=['project', 'status'], name='feedback_proj_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfeedback',
            index=models.Index(fields=['project', 'priority'], name='feedback_proj_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfeedback',
            index=models.Index(fields=['reported_by', 'created_at'], name='feedback_reporter_idx'),
        ),
        migrations.AddIndex(
            model_name='projectfeedback',
            index=models.Index(fields=['is_active', 'created_at'], name='feedback_active_created_idx'),
        ),
    ]
