"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

import sys

from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env from project root (not cwd — reliable when runserver cwd varies)
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-&r9k5p6ni*+&#kk=wv-ezcdynz6@n=gi8cn+5pjy&_!4-1^px3')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'drf_yasg',
    'django_filters',
    'channels',
    'notifications',
    'projects',
    'dpr',
    'monthly_scope',
    'accounts',
    'operations',
    'contracts',
    'invoicing',
    'contract_performance',
    'project_progress',
    'budget_performance',
    'equipment',
    'manpower',
    'cashflow',
    'cost_performance',
    'health_safety',
    'plant_machinery',
    'manpower_management',
    'drawings',
    'correspondence',
    'planned_earned_value',
    'contract_values',
    'project_quality_status',
    'construction_progress',
    'project_equipment',
    'project_dates',
    'contractors',
    'site_images.apps.SiteImagesConfig',
    'bottlenecks',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CSRF disabled for API endpoints - using JWT authentication
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom CSRF exemption for API
    'backend.middleware.CSRFMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'



# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database — use DATABASE_URL when set (Render/Neon). Fallback to SQLite for
# local tooling only; production must set DATABASE_URL (see settings_prod).
DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Base URL for generating absolute URLs (e.g., in emails)
BASE_URL = os.environ.get('RENDER_EXTERNAL_URL', os.environ.get('BASE_URL', 'http://localhost:8000'))

# -----------------------------------------------------------------------------
# CORS — allow all origins (*)
# CORS_ALLOW_ALL_ORIGINS=True; regex below supports credentialed requests
# (browser forbids Access-Control-Allow-Origin: * with credentials).
# -----------------------------------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^.+$",  # any Origin
]
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-role',
    'baggage',
    'sentry-trace',
]

CORS_EXPOSE_HEADERS = [
    'content-type',
    'authorization',
]

CORS_PREFLIGHT_MAX_AGE = 86400

# Apply CORS to all URL paths
CORS_URLS_REGEX = r'^.*$'

# Trusted origins for CSRF (must include scheme + host; add your dev servers)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:5173',
    'http://localhost:3000',
    'http://127.0.0.1:5173',
    'http://127.0.0.1:3000',
    'https://fv5k8l3m-8000.inc1.devtunnels.ms',
    'http://fv5k8l3m-8000.inc1.devtunnels.ms',
    "http://localhost:5174",
]

# Disable CSRF for API endpoints (using JWT authentication)
CSRF_COOKIE_SECURE = True  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False
CSRF_USE_SESSIONS = False
SESSION_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'core.throttling.LoginRateThrottle',
        'core.throttling.RefreshRateThrottle',
        'core.throttling.MethodScopedRateThrottle',
        'core.throttling.CreateRateThrottle',
        'core.throttling.UpdateRateThrottle',
        'core.throttling.DeleteRateThrottle',
        'core.throttling.ExportRateThrottle',
        'core.throttling.UploadRateThrottle',
        'core.throttling.NotificationRateThrottle',
        'core.throttling.SearchRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/min',
        'user': '300/min',
        'login': '5/min',
        'refresh': '30/min',
        'create': '60/min',
        'update': '120/min',
        'delete': '20/min',
        'export': '10/min',
        'upload': '10/min',
        'alerts': '120/min',
        'search': '150/min',
    },
    'EXCEPTION_HANDLER': 'core.exception_handlers.pmc_exception_handler',
}

if "test" in sys.argv:
    REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
        "anon": "10000/min",
        "user": "10000/min",
        "login": "10000/min",
        "refresh": "10000/min",
        "create": "10000/min",
        "update": "10000/min",
        "delete": "10000/min",
        "export": "10000/min",
        "upload": "10000/min",
        "alerts": "10000/min",
        "search": "10000/min",
    }

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT access token. Example: Bearer <access_token>',
        },
    },
    'USE_SESSION_AUTH': False,
}



# Caching Configuration — used by DRF throttling and API caches.
# Prefer Redis when REDIS_URL is reachable; fall back to LocMem (dev/tests).
def _build_cache_settings():
    locmem = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
    if "test" in sys.argv:
        return locmem
    if os.environ.get("USE_LOCMEM_CACHE", "").lower() == "true":
        return locmem

    redis_url = os.environ.get("REDIS_URL") or os.environ.get("REDIS_CACHE_URL")
    if not redis_url:
        return locmem

    try:
        import redis

        client = redis.from_url(redis_url, socket_connect_timeout=1)
        client.ping()
    except Exception:
        return locmem

    return {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": redis_url,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
        }
    }


CACHES = _build_cache_settings()

# Cache settings for API endpoints
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 300  # 5 minutes default



# ==============================
# CHANNELS CONFIGURATION
# ==============================
import os

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# ==============================
# EMAIL CONFIGURATION
# ==============================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ==============================
# CLOUDINARY (Site Progress Images — fallback; disabled when SITE_IMAGE_S3_ONLY=True)
# Credentials only — SDK config lives in core/cloudinary_config.py
# ==============================
SITE_IMAGE_S3_ONLY = os.environ.get('SITE_IMAGE_S3_ONLY', 'False').lower() == 'true'

if SITE_IMAGE_S3_ONLY:
    CLOUDINARY_CLOUD_NAME = ''
    CLOUDINARY_API_KEY = ''
    CLOUDINARY_API_SECRET = ''
else:
    CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME', '')
    CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY', '')
    CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET', '')

# ==============================
# AWS S3 (Site Progress Images — primary storage)
# Set credentials via environment variables only (never commit secrets).
# ==============================
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'pmcproject')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'ap-south-1')
AWS_S3_UPLOAD_PREFIX = os.environ.get('AWS_S3_UPLOAD_PREFIX', 'upload')
AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '')
# Primary: s3 | cloudinary (falls back to the other unless SITE_IMAGE_S3_ONLY=True)
SITE_IMAGE_STORAGE_PRIMARY = os.environ.get('SITE_IMAGE_STORAGE_PRIMARY', 's3')



