# Generated by Django 6.0.2 on 2026-03-18 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSafetyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Name of the project', max_length=255)),
                ('report_date', models.DateField(help_text='Date of the report')),
                ('total_manhours', models.FloatField(help_text='Total manhours worked', validators=[django.core.validators.MinValueValidator(0)])),
                ('fatalities', models.IntegerField(default=0, help_text='Number of fatalities', validators=[django.core.validators.MinValueValidator(0)])),
                ('significant', models.IntegerField(default=0, help_text='Number of significant incidents', validators=[django.core.validators.MinValueValidator(0)])),
                ('major', models.IntegerField(default=0, help_text='Number of major incidents', validators=[django.core.validators.MinValueValidator(0)])),
                ('minor', models.IntegerField(default=0, help_text='Number of minor incidents', validators=[django.core.validators.MinValueValidator(0)])),
                ('near_miss', models.IntegerField(default=0, help_text='Number of near miss incidents', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health & Safety Report',
                'verbose_name_plural': 'Health & Safety Reports',
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['project_name', '-report_date'], name='health_safe_project_1ea987_idx'), models.Index(fields=['-report_date'], name='health_safe_report__c40c2d_idx')],
            },
        ),
    ]
