# Generated by Django 5.0.1 on 2026-04-14 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_safety', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthsafetyreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='healthsafetyreport',
            name='project_name',
            field=models.CharField(db_index=True, help_text='Name of the project', max_length=255),
        ),
        migrations.AlterField(
            model_name='healthsafetyreport',
            name='total_manhours',
            field=models.DecimalField(decimal_places=2, help_text='Total manhours worked', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='healthsafetyreport',
            constraint=models.UniqueConstraint(fields=('project_name', 'report_date'), name='unique_project_date_hs'),
        ),
    ]
