# Generated by Django 5.2.13 on 2026-05-27 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_safety', '0002_alter_healthsafetyreport_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSERecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_index=True, help_text='Unique project name for this HSE record', max_length=255, unique=True)),
                ('fatalities', models.PositiveIntegerField(default=0, help_text='Number of fatality incidents', validators=[django.core.validators.MinValueValidator(0)])),
                ('significant', models.PositiveIntegerField(default=0, help_text='Number of significant incidents', validators=[django.core.validators.MinValueValidator(0)])),
                ('major', models.PositiveIntegerField(default=0, help_text='Number of major incidents', validators=[django.core.validators.MinValueValidator(0)])),
                ('minor', models.PositiveIntegerField(default=0, help_text='Number of minor incidents', validators=[django.core.validators.MinValueValidator(0)])),
                ('nearMiss', models.PositiveIntegerField(default=0, help_text='Number of near-miss incidents', validators=[django.core.validators.MinValueValidator(0)])),
                ('totalManhours', models.DecimalField(decimal_places=2, default=0, help_text='Total manhours worked on the project', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('lossOfManhours', models.DecimalField(decimal_places=2, default=0, help_text='Total manhours lost due to incidents', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'HSE Record',
                'verbose_name_plural': 'HSE Records',
                'ordering': ['projectName'],
                'indexes': [models.Index(fields=['projectName'], name='hse_record_project_name_idx')],
            },
        ),
    ]
