# Generated by Django 5.2.13 on 2026-06-01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_safety', '0003_hserecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSafetyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, help_text='Project name for this monthly HSE record', max_length=255)),
                ('month', models.PositiveSmallIntegerField(db_index=True, help_text='Month number (1–12)')),
                ('year', models.PositiveSmallIntegerField(db_index=True, help_text='Year (e.g. 2026)')),
                ('fatalities', models.PositiveIntegerField(default=0, help_text='Number of fatality incidents this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('significant', models.PositiveIntegerField(default=0, help_text='Number of significant incidents this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('major', models.PositiveIntegerField(default=0, help_text='Number of major incidents this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('minor', models.PositiveIntegerField(default=0, help_text='Number of minor incidents this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('near_miss', models.PositiveIntegerField(default=0, help_text='Number of near-miss incidents this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_manhours', models.DecimalField(decimal_places=2, default=0, help_text='Total manhours worked this month', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('loss_of_manhours', models.DecimalField(decimal_places=2, default=0, help_text='Manhours lost due to incidents this month', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Health & Safety Record',
                'verbose_name_plural': 'Health & Safety Records',
                'db_table': 'health_safety_healthsafetyrecord',
                'ordering': ['project_name', 'year', 'month'],
                'indexes': [
                    models.Index(fields=['project_name', 'year', 'month'], name='mhse_proj_year_month_idx'),
                    models.Index(fields=['year', 'month'], name='mhse_year_month_idx'),
                ],
                'unique_together': {('project_name', 'month', 'year')},
            },
        ),
    ]
