# Generated by Django 6.0.4 on 2026-07-20 05:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_safety', '0004_healthsafetyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='average_daily_manpower',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average daily manpower for the month', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='dangerous_occurrences',
            field=models.PositiveIntegerField(default=0, help_text='Dangerous occurrences this month', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='external_training_count',
            field=models.PositiveIntegerField(default=0, help_text='External training sessions count', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='external_training_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='External training hours', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='first_aid_cases',
            field=models.PositiveIntegerField(default=0, help_text='First aid cases this month', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='internal_training_count',
            field=models.PositiveIntegerField(default=0, help_text='Internal training sessions count', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='internal_training_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Internal training hours', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='man_days_worked',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto: average_daily_manpower × working_days', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='man_hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Auto: man_days_worked × 8 (synced to total_manhours)', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='medical_checkup_staff',
            field=models.PositiveIntegerField(default=0, help_text='Medical checkups — staff', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='medical_checkup_total',
            field=models.PositiveIntegerField(default=0, help_text='Auto: medical_checkup_workers + medical_checkup_staff', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='medical_checkup_workers',
            field=models.PositiveIntegerField(default=0, help_text='Medical checkups — workers', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='medical_treatment_cases',
            field=models.PositiveIntegerField(default=0, help_text='Medical treatment cases this month', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='mock_drills',
            field=models.PositiveIntegerField(default=0, help_text='Mock drills conducted this month', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='reportable_accident_lti',
            field=models.PositiveIntegerField(default=0, help_text='Reportable accidents (LTI) this month', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='utility_damage',
            field=models.PositiveIntegerField(default=0, help_text='Utility damage incidences this month', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='healthsafetyrecord',
            name='working_days',
            field=models.PositiveIntegerField(default=0, help_text='Working days in the month (must be > 0 when entering manpower stats)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='healthsafetyrecord',
            name='loss_of_manhours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manhours lost due to incidents this month (Man Hours Lost)', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
