# Generated by Django 6.0 on 2026-07-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_safety', '0005_monthly_hse_statistics'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hserecord',
            name='hse_record_project_name_idx',
        ),
    ]
