# Generated by Django 5.2.13 on 2026-05-27 05:30

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_index=True, help_text='Project name for this contract value record', max_length=255)),
                ('contractType', models.CharField(choices=[('SCL', 'SCL'), ('Contractor', 'Contractor')], db_index=True, help_text='Contract type: "SCL" or "Contractor"', max_length=50)),
                ('originalContractValue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Original contract value (>= 0)', max_digits=20)),
                ('approvedVO', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Approved Variation Order amount (>= 0)', max_digits=20)),
                ('potentialPendingVO', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Potential / Pending Variation Order amount (>= 0)', max_digits=20)),
                ('approvedVOPercentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-calculated: (approvedVO / originalContractValue) * 100. 0.00 when originalContractValue = 0.', max_digits=10)),
                ('revisedContractValue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-calculated: originalContractValue + approvedVO', max_digits=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Contract Value',
                'verbose_name_plural': 'Contract Values',
                'ordering': ['projectName', 'contractType'],
                'indexes': [models.Index(fields=['projectName'], name='cv_project_name_idx'), models.Index(fields=['contractType'], name='cv_contract_type_idx'), models.Index(fields=['projectName', 'contractType'], name='cv_project_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('projectName', 'contractType'), name='cv_unique_project_contract_type')],
            },
        ),
    ]
