# Generated by Django 5.2.13 on 2026-06-02

from decimal import Decimal

from django.db import migrations, models


def migrate_legacy_contract_fields(apps, schema_editor):
    ContractValue = apps.get_model("contract_values", "ContractValue")
    for record in ContractValue.objects.all().order_by("id"):
        record.excess_value = record.approvedVO or Decimal("0.00")
        record.saving = record.potentialPendingVO or Decimal("0.00")
        if record.contract_type == "Contractor":
            record.contract_type = "CONTRACTOR"
        record.save(update_fields=["excess_value", "saving", "contract_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("contract_values", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contractvalue",
            name="cv_unique_project_contract_type",
        ),
        migrations.RemoveIndex(
            model_name="contractvalue",
            name="cv_project_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="contractvalue",
            name="cv_contract_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="contractvalue",
            name="cv_project_type_idx",
        ),
        migrations.RenameField(
            model_name="contractvalue",
            old_name="projectName",
            new_name="project_name",
        ),
        migrations.RenameField(
            model_name="contractvalue",
            old_name="contractType",
            new_name="contract_type",
        ),
        migrations.RenameField(
            model_name="contractvalue",
            old_name="originalContractValue",
            new_name="original_contract_value",
        ),
        migrations.AlterModelOptions(
            name="contractvalue",
            options={
                "ordering": ["project_name", "contract_type"],
                "verbose_name": "Contract Value",
                "verbose_name_plural": "Contract Values",
            },
        ),
        migrations.AddConstraint(
            model_name="contractvalue",
            constraint=models.UniqueConstraint(
                fields=("project_name", "contract_type"),
                name="cv_unique_project_contract_type",
            ),
        ),
        migrations.AddField(
            model_name="contractvalue",
            name="excess_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Excess value (>= 0)",
                max_digits=20,
            ),
        ),
        migrations.AddField(
            model_name="contractvalue",
            name="saving",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Saving amount (>= 0)",
                max_digits=20,
            ),
        ),
        migrations.RunPython(migrate_legacy_contract_fields, migrations.RunPython.noop),
        migrations.RemoveField(model_name="contractvalue", name="approvedVO"),
        migrations.RemoveField(model_name="contractvalue", name="potentialPendingVO"),
        migrations.RemoveField(model_name="contractvalue", name="approvedVOPercentage"),
        migrations.RemoveField(model_name="contractvalue", name="revisedContractValue"),
        migrations.AlterField(
            model_name="contractvalue",
            name="contract_type",
            field=models.CharField(
                choices=[("SCL", "SCL"), ("CONTRACTOR", "CONTRACTOR")],
                db_index=True,
                help_text='Contract type: "SCL" or "CONTRACTOR"',
                max_length=50,
            ),
        ),
    ]
