# Generated by Django 6.0.4 on 2026-06-10 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_values', '0002_revised_value_excess_saving'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contractvalue',
            name='cv_project_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='contractvalue',
            name='cv_contract_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='contractvalue',
            name='cv_project_type_idx',
        ),
        migrations.AlterField(
            model_name='contractvalue',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='contractvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='contractvalue',
            index=models.Index(fields=['project_name'], name='cv_project_name_idx'),
        ),
        migrations.AddIndex(
            model_name='contractvalue',
            index=models.Index(fields=['contract_type'], name='cv_contract_type_idx'),
        ),
        migrations.AddIndex(
            model_name='contractvalue',
            index=models.Index(fields=['project_name', 'contract_type'], name='cv_project_type_idx'),
        ),
    ]
