# Generated by Django 5.2.13 on 2026-07-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_values', '0004_contractvalue_multi_contractor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractvalue',
            options={'ordering': ['project_name', 'contract_type', 'contractor_name'], 'verbose_name': 'Contract Value', 'verbose_name_plural': 'Contract Values'},
        ),
    ]
