# Generated by Django 5.2.13 on 2026-07-01 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract_values', '0005_alter_contractvalue_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contractvalue',
            name='cv_unique_contractor_name_per_project',
        ),
    ]
