# Generated by Django 6.0 on 2026-07-23 07:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_values', '0007_contractvalue_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractvalue',
            name='cos',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='COS (Change of Scope) amount (>= 0). Manually editable; not used in revised_value formula.', max_digits=20),
        ),
    ]
