# Generated by Django 5.2.13 on 2026-05-28 04:05

import construction_progress.models.construction_progress
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_index=True, help_text='Project name this progress record belongs to', max_length=255)),
                ('progressMonth', models.CharField(db_index=True, help_text="Month of progress in YYYY-MM format (e.g. '2026-05')", max_length=7, validators=[construction_progress.models.construction_progress._validate_progress_month])),
                ('plannedProgress', models.FloatField(default=0.0, help_text='Planned progress percentage for this month (0–100)')),
                ('actualProgress', models.FloatField(default=0.0, help_text='Actual progress percentage achieved this month (0–100)')),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional remarks — delay reasons, site conditions, etc.')),
                ('variance', models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: actualProgress - plannedProgress. Negative = behind schedule, positive = ahead of schedule.')),
                ('performancePercentage', models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: (actualProgress / plannedProgress) * 100. 0.0 when plannedProgress = 0.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Monthly Construction Progress',
                'verbose_name_plural': 'Monthly Construction Progress Records',
                'ordering': ['projectName', 'progressMonth'],
                'indexes': [models.Index(fields=['projectName'], name='conprog_project_name_idx'), models.Index(fields=['progressMonth'], name='conprog_month_idx'), models.Index(fields=['projectName', 'progressMonth'], name='conprog_project_month_idx')],
                'unique_together': {('projectName', 'progressMonth')},
            },
        ),
    ]
