# Generated by Django 6.0 on 2026-07-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction_progress', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='constructionprogress',
            name='conprog_project_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='constructionprogress',
            name='conprog_project_month_idx',
        ),
    ]
