# Generated by Django 6.0 on 2026-03-17 05:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Name of the project', max_length=255)),
                ('job_no', models.CharField(help_text='Job number or reference code', max_length=100)),
                ('report_date', models.DateField(help_text='Date of the report')),
                ('unresolved_issues', models.TextField(blank=True, help_text='Any unresolved issues')),
                ('pending_letters', models.TextField(blank=True, help_text='Pending letters or communications')),
                ('quality_status', models.TextField(blank=True, help_text='Quality status information')),
                ('next_day_incident', models.TextField(blank=True, help_text='Incidents planned for next day')),
                ('bill_status', models.TextField(blank=True, help_text='Billing status')),
                ('gfc_status', models.TextField(blank=True, help_text='GFC (Good for Construction) status')),
                ('issued_by', models.CharField(help_text='Person who issued the report', max_length=255)),
                ('designation', models.CharField(help_text='Designation of the issuer', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when report was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when report was last updated')),
            ],
            options={
                'verbose_name': 'Daily Progress Report',
                'verbose_name_plural': 'Daily Progress Reports',
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['project_name', '-report_date'], name='dpr_dailypr_project_df1436_idx'), models.Index(fields=['-report_date'], name='dpr_dailypr_report__e8bb29_idx')],
            },
        ),
        migrations.CreateModel(
            name='DPRActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the activity')),
                ('activity', models.TextField(help_text='Description of the activity')),
                ('deliverables', models.TextField(blank=True, help_text='Deliverables for this activity')),
                ('target_achieved', models.FloatField(default=0.0, help_text='Target achieved percentage (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('next_day_plan', models.TextField(blank=True, help_text='Plan for the next day')),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('dpr', models.ForeignKey(help_text='Parent Daily Progress Report', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dpr.dailyprogressreport')),
            ],
            options={
                'verbose_name': 'DPR Activity',
                'verbose_name_plural': 'DPR Activities',
                'ordering': ['date', 'id'],
            },
        ),
    ]
