# Generated by Django 6.0.2 on 2026-03-30 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogressreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when DPR was finally approved', null=True),
        ),
        migrations.AddField(
            model_name='dailyprogressreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who finally approved the DPR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dprs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyprogressreport',
            name='current_approver_role',
            field=models.CharField(blank=True, help_text='Role that should currently approve this DPR', max_length=50),
        ),
        migrations.AddField(
            model_name='dailyprogressreport',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected the DPR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_dprs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyprogressreport',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if status is rejected'),
        ),
        migrations.AddField(
            model_name='dailyprogressreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_team_lead', 'Pending Team Lead Approval'), ('pending_coordinator', 'Pending Coordinator Approval'), ('pending_pmc_head', 'Pending PMC Head Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current approval status of the DPR', max_length=25),
        ),
        migrations.AddField(
            model_name='dailyprogressreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted the DPR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_dprs', to=settings.AUTH_USER_MODEL),
        ),
    ]
