# Generated by Django 5.0.1 on 2026-04-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0003_alter_dailyprogressreport_current_approver_role_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailyprogressreport',
            constraint=models.UniqueConstraint(
                fields=('project_name', 'report_date'),
                name='unique_project_date_dpr'
            ),
        ),
    ]