# Generated by Django 5.0.1 on 2026-04-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0004_add_unique_constraint_dailyprogressreport'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyprogressreport',
            name='unique_project_date_dpr',
        ),
        migrations.AlterField(
            model_name='dpractivity',
            name='target_achieved',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Target achieved percentage', max_digits=5),
        ),
    ]
