# Generated by Django 6.0.4 on 2026-05-08 07:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0005_remove_unique_constraint'),
        ('monthly_scope', '0006_monthlyscopework_cumulative_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpractivity',
            name='cumulative_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cumulative executed quantity for this scope', max_digits=12),
        ),
        migrations.AddField(
            model_name='dpractivity',
            name='executed_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity executed today', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='dpractivity',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Progress percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='dpractivity',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining quantity to complete the scope', max_digits=12),
        ),
        migrations.AddField(
            model_name='dpractivity',
            name='scope',
            field=models.ForeignKey(blank=True, help_text='Linked Monthly Scope Work', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dpr_activities', to='monthly_scope.monthlyscopework'),
        ),
        migrations.AlterField(
            model_name='dpractivity',
            name='target_achieved',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Target achieved percentage (legacy)', max_digits=5),
        ),
    ]
