# Generated by Django 6.0.4 on 2026-05-08 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0006_dpractivity_cumulative_quantity_and_more'),
        ('monthly_scope', '0006_monthlyscopework_cumulative_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpractivity',
            options={'ordering': ['id'], 'verbose_name': 'DPR Activity', 'verbose_name_plural': 'DPR Activities'},
        ),
        migrations.AlterUniqueTogether(
            name='dpractivity',
            unique_together={('dpr', 'scope')},
        ),
        migrations.AddField(
            model_name='dpractivity',
            name='next_day_planned_work',
            field=models.TextField(blank=True, help_text='Planned work for next day'),
        ),
        migrations.AlterField(
            model_name='dpractivity',
            name='executed_quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity executed today', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddIndex(
            model_name='dpractivity',
            index=models.Index(fields=['dpr', 'scope'], name='dpr_dpracti_dpr_id_aaee7b_idx'),
        ),
        migrations.AddIndex(
            model_name='dpractivity',
            index=models.Index(fields=['scope', 'dpr'], name='dpr_dpracti_scope_i_e2d19d_idx'),
        ),
        migrations.RemoveField(
            model_name='dpractivity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='dpractivity',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dpractivity',
            name='deliverables',
        ),
        migrations.RemoveField(
            model_name='dpractivity',
            name='next_day_plan',
        ),
        migrations.RemoveField(
            model_name='dpractivity',
            name='target_achieved',
        ),
    ]
