# Generated by Django 6.0.4 on 2026-05-08 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0007_refactor_dpr_activity_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogressreport',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this DPR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dprs', to=settings.AUTH_USER_MODEL),
        ),
    ]
