# Generated by Django 6.0 on 2026-07-31 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpr', '0008_add_created_by_to_dpr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogressreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_team_lead', 'Pending Team Lead Approval'), ('pending_coordinator', 'Pending PMC Manager Approval'), ('pending_pmc_head', 'Pending PMC Head Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', help_text='Current approval status of the DPR', max_length=25),
        ),
        migrations.AddIndex(
            model_name='dailyprogressreport',
            index=models.Index(fields=['status', '-report_date'], name='dpr_status_report_date_idx'),
        ),
    ]
