# Generated by Django 6.0 on 2026-08-10 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('deleted', 'Deleted')], db_index=True, default='processing', max_length=20)),
                ('processing_error', models.CharField(blank=True, default='', max_length=500)),
                ('temp_s3_key', models.CharField(blank=True, default='', max_length=512)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('original_file_size', models.BigIntegerField(blank=True, null=True)),
                ('original_content_type', models.CharField(blank=True, default='', max_length=100)),
                ('optimized_s3_key', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('video_url', models.URLField(blank=True, default='', max_length=1024)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Optimized file size in bytes', null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('compression_ratio', models.FloatField(blank=True, help_text='original_size / optimized_size when both known', null=True)),
                ('processing_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_tutorial_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutorial Video',
                'verbose_name_plural': 'Tutorial Videos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'status', '-created_at'], name='tutorial_active_status_idx')],
            },
        ),
    ]
