# Generated by Django 6.0.4 on 2026-05-08 04:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0009_alter_project_options_alter_project_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=255, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scope Category',
                'verbose_name_plural': 'Scope Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScopeSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subcategory name', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subcategory is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Parent category', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='monthly_scope.scopecategory')),
            ],
            options={
                'verbose_name': 'Scope Subcategory',
                'verbose_name_plural': 'Scope Subcategories',
                'ordering': ['category', 'display_order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyScopeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Month for this scope (first day of the month)')),
                ('description', models.TextField(blank=True, help_text='Description of the scope')),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., m3, nos, km)', max_length=50)),
                ('planned_quantity', models.DecimalField(decimal_places=2, help_text='Planned quantity', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('section', models.CharField(blank=True, help_text='Section name', max_length=255)),
                ('location', models.CharField(blank=True, help_text='Location details', max_length=255)),
                ('start_date', models.DateField(help_text='Planned start date')),
                ('end_date', models.DateField(help_text='Planned end date')),
                ('custom_category_name', models.CharField(blank=True, help_text="Custom category name when 'Other' is selected", max_length=255)),
                ('custom_subcategory_name', models.CharField(blank=True, help_text="Custom subcategory name when 'Other' is selected", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', help_text='Current status of the scope', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this scope', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scopes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this scope belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scopes', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this scope', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scopes', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Scope category', on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='monthly_scope.scopecategory')),
                ('subcategory', models.ForeignKey(help_text='Scope subcategory', on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='monthly_scope.scopesubcategory')),
            ],
            options={
                'verbose_name': 'Monthly Scope of Work',
                'verbose_name_plural': 'Monthly Scopes of Work',
                'ordering': ['project', 'month', 'category', 'subcategory'],
            },
        ),
        migrations.CreateModel(
            name='ScopeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When the assignment was made')),
                ('assigned_by', models.ForeignKey(blank=True, help_text='User who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(help_text='Scope being assigned', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='monthly_scope.monthlyscopework')),
                ('site_engineer', models.ForeignKey(help_text='Site Engineer assigned to this scope', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scope Assignment',
                'verbose_name_plural': 'Scope Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('scope', 'site_engineer')},
            },
        ),
        migrations.AddIndex(
            model_name='monthlyscopework',
            index=models.Index(fields=['project', 'month'], name='monthly_sco_project_1d815c_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyscopework',
            index=models.Index(fields=['category', 'subcategory'], name='monthly_sco_categor_3132b2_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyscopework',
            index=models.Index(fields=['status'], name='monthly_sco_status_3a353b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyscopework',
            unique_together={('project', 'month', 'category', 'subcategory', 'description')},
        ),
    ]
