# Generated by Django 6.0.4 on 2026-05-08 04:57

from django.db import migrations


def populate_initial_categories(apps, schema_editor):
    ScopeCategory = apps.get_model('monthly_scope', 'ScopeCategory')
    ScopeSubCategory = apps.get_model('monthly_scope', 'ScopeSubCategory')

    # Define categories and their subcategories
    categories_data = [
        {
            'name': 'Foundation',
            'display_order': 1,
            'subcategories': [
                {'name': 'Soil Investigation', 'display_order': 1},
                {'name': 'Utility Identification', 'display_order': 2},
                {'name': 'Piles', 'display_order': 3},
                {'name': 'Piles 1000mm Dia', 'display_order': 4},
                {'name': 'Piles 1200mm Dia', 'display_order': 5},
                {'name': 'Pile Cap', 'display_order': 6},
                {'name': 'Other', 'display_order': 7},
            ]
        },
        {
            'name': 'Substructure',
            'display_order': 2,
            'subcategories': [
                {'name': 'Piers', 'display_order': 1},
                {'name': 'Piercap', 'display_order': 2},
                {'name': 'Pedestal', 'display_order': 3},
                {'name': 'Other', 'display_order': 4},
            ]
        },
        {
            'name': 'Superstructure',
            'display_order': 3,
            'subcategories': [
                {'name': 'Segment Casting', 'display_order': 1},
                {'name': 'Composite Casting', 'display_order': 2},
                {'name': 'Other', 'display_order': 3},
            ]
        },
        {
            'name': 'RE Walls & Approach',
            'display_order': 4,
            'subcategories': [
                {'name': 'A1 Side', 'display_order': 1},
                {'name': 'A2 Side', 'display_order': 2},
                {'name': 'Other', 'display_order': 3},
            ]
        },
        {
            'name': 'Slip Road',
            'display_order': 5,
            'subcategories': [
                {'name': 'Drain', 'display_order': 1},
                {'name': 'Subgrade', 'display_order': 2},
                {'name': 'GSB', 'display_order': 3},
                {'name': 'DLC', 'display_order': 4},
                {'name': 'PQC', 'display_order': 5},
                {'name': 'Other', 'display_order': 6},
            ]
        },
    ]

    for category_data in categories_data:
        category = ScopeCategory.objects.create(
            name=category_data['name'],
            display_order=category_data['display_order']
        )

        for subcategory_data in category_data['subcategories']:
            ScopeSubCategory.objects.create(
                category=category,
                name=subcategory_data['name'],
                display_order=subcategory_data['display_order']
            )


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_scope', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_initial_categories),
    ]
