# Generated by Django 6.0.4 on 2026-05-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_scope', '0002_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopesubcategory',
            name='default_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default quantity for this subcategory', max_digits=12, null=True),
        ),
    ]
