# Generated by Django 6.0.4 on 2026-05-08 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_scope', '0003_scopesubcategory_default_quantity'),
        ('projects', '0009_alter_project_options_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyscopework',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Scope category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='monthly_scope.scopecategory'),
        ),
        migrations.AlterField(
            model_name='monthlyscopework',
            name='end_date',
            field=models.DateField(blank=True, help_text='Planned end date', null=True),
        ),
        migrations.AlterField(
            model_name='monthlyscopework',
            name='month',
            field=models.DateField(blank=True, help_text='Month for this scope (first day of the month)', null=True),
        ),
        migrations.AlterField(
            model_name='monthlyscopework',
            name='planned_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Planned quantity', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyscopework',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this scope belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scopes', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='monthlyscopework',
            name='start_date',
            field=models.DateField(blank=True, help_text='Planned start date', null=True),
        ),
        migrations.AlterField(
            model_name='monthlyscopework',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Scope subcategory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='monthly_scope.scopesubcategory'),
        ),
        migrations.AlterField(
            model_name='monthlyscopework',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit of measurement (e.g., m3, nos, km)', max_length=50),
        ),
    ]
