# Generated by Django 6.0.4 on 2026-05-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_scope', '0004_alter_monthlyscopework_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyscopework',
            unique_together=set(),
        ),
    ]
