# Generated by Django 6.0.4 on 2026-05-08 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_scope', '0005_alter_monthlyscopework_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyscopework',
            name='cumulative_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cumulative executed quantity from all DPRs', max_digits=12),
        ),
        migrations.AddField(
            model_name='monthlyscopework',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Progress percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='monthlyscopework',
            name='remaining_quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining quantity to complete the scope', max_digits=12),
        ),
    ]
