# Generated by Django 6.0 on 2026-07-31 04:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monthly_scope', '0006_monthlyscopework_cumulative_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scopeassignment',
            index=models.Index(fields=['site_engineer', 'scope'], name='scope_asgn_se_scope_idx'),
        ),
    ]
