# Generated by Django 5.0.1 on 2026-04-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectequipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='projectequipment',
            name='month',
            field=models.DateField(db_index=True, help_text='First day of the month for this record'),
        ),
        migrations.AddIndex(
            model_name='projectequipment',
            index=models.Index(fields=['project_name', 'month'], name='equipment_project_month_idx'),
        ),
    ]
