# Generated by Django 5.0.1 on 2026-04-10 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_performance', '0001_initial'),
        ('projects', '0008_project_approved_vo_project_assigned_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcostperformance',
            options={'ordering': ['project__name', 'month_year'], 'verbose_name': 'Project cost performance', 'verbose_name_plural': 'Project cost performance records'},
        ),
        migrations.RemoveConstraint(
            model_name='projectcostperformance',
            name='costperf_unique_project_month_year',
        ),
        migrations.AddField(
            model_name='projectcostperformance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_performances', to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='projectcostperformance',
            constraint=models.UniqueConstraint(fields=('project', 'month_year'), name='costperf_unique_project_month_year'),
        ),
    ]
