# Generated by Django 5.0.1 on 2026-04-14 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_performance', '0004_optimize_performance_precision'),
        ('projects', '0009_alter_project_options_alter_project_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcostperformance',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_performances', to='projects.project'),
        ),
    ]
