# Generated by Django 6.0 on 2026-07-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost_performance', '0005_alter_projectcostperformance_project'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='projectcostperformance',
            name='costperf_project_month_idx',
        ),
    ]
