# Generated by Django 6.0 on 2026-03-17 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProgressStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Project name for this progress record', max_length=255)),
                ('progress_month', models.DateField(help_text='Month for this progress record (first day of the month)')),
                ('monthly_plan', models.FloatField(default=0.0, help_text='Planned progress for this month (percentage 0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('cumulative_plan', models.FloatField(default=0.0, help_text='Cumulative planned progress from project start to this month (percentage 0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('monthly_actual', models.FloatField(default=0.0, help_text='Actual progress achieved in this month (percentage 0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('cumulative_actual', models.FloatField(default=0.0, help_text='Cumulative actual progress from project start to this month (percentage 0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('created_by', models.CharField(help_text='User who created this record', max_length=255)),
                ('updated_by', models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project Progress Status',
                'verbose_name_plural': 'Project Progress Status',
                'ordering': ['project_name', 'progress_month'],
                'indexes': [models.Index(fields=['project_name', 'progress_month'], name='project_pro_project_7ba0ee_idx'), models.Index(fields=['progress_month'], name='project_pro_progres_c1a969_idx')],
                'unique_together': {('project_name', 'progress_month')},
            },
        ),
    ]
