# Generated by Django 6.0 on 2026-08-11 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0018_billing_status_db_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(db_index=True, help_text='When the reminder is due (assignee is notified at/after this time)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('snoozed_until', models.DateTimeField(blank=True, db_index=True, help_text='If set, effective due time for notifications/lists', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When the due notification was last sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='User who should receive the reminder notification', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_reminders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='projects.project')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['due_at', 'id'],
                'indexes': [models.Index(fields=['status', 'due_at'], name='rem_status_due_idx'), models.Index(fields=['project', 'status', 'due_at'], name='rem_proj_status_due_idx'), models.Index(fields=['assigned_to', 'status', 'due_at'], name='rem_assignee_due_idx'), models.Index(fields=['status', 'notified_at', 'due_at'], name='rem_notify_scan_idx')],
            },
        ),
    ]
