# Generated by Django 5.2.13 on 2026-05-28 04:17

import django.utils.timezone
import project_equipment.models.project_equipment
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_index=True, help_text='Project name this equipment record belongs to', max_length=255)),
                ('equipmentMonth', models.CharField(db_index=True, help_text="Month of equipment tracking in YYYY-MM format (e.g. '2026-05')", max_length=7, validators=[project_equipment.models.project_equipment._validate_equipment_month])),
                ('plannedEquipment', models.PositiveIntegerField(default=0, help_text='Planned equipment count for this month')),
                ('actualEquipment', models.PositiveIntegerField(default=0, help_text='Actual equipment deployed this month')),
                ('remarks', models.TextField(blank=True, default='', help_text='Optional remarks — shortage reasons, maintenance issues, etc.')),
                ('variance', models.IntegerField(default=0, editable=False, help_text='Auto-calculated: actualEquipment - plannedEquipment. Negative = shortfall, positive = surplus.')),
                ('performancePercentage', models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: (actualEquipment / plannedEquipment) * 100. 0.0 when plannedEquipment = 0.')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Monthly Project Equipment',
                'verbose_name_plural': 'Monthly Project Equipment Records',
                'ordering': ['projectName', 'equipmentMonth'],
                'indexes': [models.Index(fields=['projectName'], name='pe_project_name_idx'), models.Index(fields=['equipmentMonth'], name='pe_equipment_month_idx'), models.Index(fields=['projectName', 'equipmentMonth'], name='pe_project_month_idx')],
                'unique_together': {('projectName', 'equipmentMonth')},
            },
        ),
    ]
