# Generated by Django 6.0 on 2026-03-17 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_engineer_type', models.CharField(blank=True, choices=[('site_engineer', 'Site Engineer'), ('billing_site_engineer', 'Billing Site Engineer'), ('qaqc_site_engineer', 'QAQC Site Engineer')], help_text='Type of Site Engineer (only for Site Engineers)', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
