# Generated by Django 5.0.1 on 2026-04-14 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Notification message content')),
                ('notification_type', models.CharField(choices=[('project_assigned', 'Project Assigned'), ('dpr_submitted', 'DPR Submitted'), ('dpr_approved', 'DPR Approved'), ('dpr_rejected', 'DPR Rejected')], help_text='Type of notification', max_length=20)),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification was created')),
                ('user', models.ForeignKey(help_text='User who received the notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
