# Generated by Django 5.2.13 on 2026-07-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_billing_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_assigned', 'Project Assigned'), ('dpr_submitted', 'DPR Submitted'), ('dpr_approved', 'DPR Approved'), ('dpr_rejected', 'DPR Rejected'), ('BILLING_UPDATE', 'Billing Data Updated'), ('MEETING_DOCUMENT', 'Meeting Document Uploaded')], help_text='Type of notification', max_length=30),
        ),
    ]
