# Generated by Django 6.0.4 on 2026-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project_assigned', 'Project Assigned'), ('dpr_submitted', 'DPR Submitted'), ('dpr_approved', 'DPR Approved'), ('dpr_rejected', 'DPR Rejected'), ('BILLING_UPDATE', 'Billing Data Updated'), ('MEETING_DOCUMENT', 'Meeting Document Uploaded'), ('CORRESPONDENCE_ATTACHMENT', 'Correspondence Document Uploaded')], help_text='Type of notification', max_length=30),
        ),
    ]
