# Generated by Django 6.0.4 on 2026-07-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='site_engineer_type',
            field=models.CharField(blank=True, choices=[('site_engineer', 'Site Engineer'), ('billing_site_engineer', 'Billing Site Engineer'), ('qaqc_site_engineer', 'QAQC Site Engineer'), ('hse_site_engineer', 'HSE Site Engineer')], help_text='Type of Site Engineer (only for Site Engineers)', max_length=50, null=True),
        ),
    ]
