# Generated by Django 6.0 on 2026-07-27 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_project_hse_site_engineer'),
        ('projects', '0014_project_merged_into'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_username', models.CharField(blank=True, default='', help_text='Snapshot of target username (survives deletion)', max_length=150)),
                ('target_role', models.CharField(blank=True, default='', help_text='Role of the target user at action time', max_length=100)),
                ('project_names', models.TextField(blank=True, default='', help_text='Comma-separated project names involved in the action')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('password_changed', 'Password Changed'), ('password_reset', 'Password Reset'), ('projects_assigned', 'Projects Assigned'), ('status_changed', 'Status Changed'), ('deleted', 'Deleted')], db_index=True, max_length=40)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, help_text='HO/Admin who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_management_actions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Primary project related to the action (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_management_audit_logs', to='projects.project')),
                ('target_user', models.ForeignKey(blank=True, help_text='User that was managed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_management_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Management Audit Log',
                'verbose_name_plural': 'User Management Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='accounts_us_action_eee921_idx'), models.Index(fields=['target_username'], name='accounts_us_target__1fd3c3_idx')],
            },
        ),
    ]
