# Generated by Django 6.0 on 2026-07-31 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_optimize_cashflow_model'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cashflow',
            name='cashflow_project_month_idx',
        ),
    ]
