# Generated by Django 6.0 on 2026-03-17 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Project name for this invoicing record', max_length=255)),
                ('gross_billed', models.DecimalField(decimal_places=2, default=0, help_text='Total amount billed including VAT', max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_billed_without_vat', models.DecimalField(decimal_places=2, default=0, help_text='Net amount billed excluding VAT', max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_collected', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually collected', max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_due', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding amount (calculated: Net Billed W/O VAT - Net Collected)', max_digits=18)),
                ('created_by', models.CharField(help_text='User who created this record', max_length=255)),
                ('updated_by', models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoicing Information',
                'verbose_name_plural': 'Invoicing Information',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_name', '-created_at'], name='invoicing_i_project_b594ae_idx')],
            },
        ),
    ]
