# Generated by Django 5.0.1 on 2026-04-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicinginformation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='invoicinginformation',
            name='project_name',
            field=models.CharField(db_index=True, help_text='Project name for this invoicing record', max_length=255),
        ),
        migrations.AddIndex(
            model_name='invoicinginformation',
            index=models.Index(fields=['project_name', 'created_at'], name='invoicing_i_project_7c5626_idx'),
        ),
    ]
