# Generated by Django 5.2.13 on 2026-06-02

from decimal import Decimal

from django.db import migrations, models


def migrate_invoicing_to_scl_contractor(apps, schema_editor):
    InvoicingInformation = apps.get_model("invoicing", "InvoicingInformation")
    for record in InvoicingInformation.objects.all().order_by("id"):
        record.gross_certified_billed = record.netCollected or Decimal("0.00")
        if record.invoice_type == "PMC":
            record.invoice_type = "SCL"
        elif record.invoice_type == "Contractor":
            record.invoice_type = "CONTRACTOR"
        record.save(
            update_fields=["gross_certified_billed", "invoice_type"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0003_refactor_add_invoice_type_camelcase"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoicinginformation",
            name="inv_unique_project_invoice_type",
        ),
        migrations.RemoveIndex(
            model_name="invoicinginformation",
            name="inv_project_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoicinginformation",
            name="inv_invoice_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="invoicinginformation",
            name="inv_project_type_idx",
        ),
        migrations.RenameField(
            model_name="invoicinginformation",
            old_name="projectName",
            new_name="project_name",
        ),
        migrations.RenameField(
            model_name="invoicinginformation",
            old_name="invoiceType",
            new_name="invoice_type",
        ),
        migrations.RenameField(
            model_name="invoicinginformation",
            old_name="grossBilled",
            new_name="gross_billed",
        ),
        migrations.AlterModelOptions(
            name="invoicinginformation",
            options={
                "ordering": ["project_name", "invoice_type"],
                "verbose_name": "Invoicing Information",
                "verbose_name_plural": "Invoicing Information",
            },
        ),
        migrations.AddConstraint(
            model_name="invoicinginformation",
            constraint=models.UniqueConstraint(
                fields=("project_name", "invoice_type"),
                name="inv_unique_project_invoice_type",
            ),
        ),
        migrations.AddField(
            model_name="invoicinginformation",
            name="gross_certified_billed",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Gross certified billed amount (>= 0)",
                max_digits=20,
            ),
        ),
        migrations.RunPython(
            migrate_invoicing_to_scl_contractor,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="invoicinginformation",
            name="netBilledWithoutVAT",
        ),
        migrations.RemoveField(
            model_name="invoicinginformation",
            name="netCollected",
        ),
        migrations.RemoveField(
            model_name="invoicinginformation",
            name="netDue",
        ),
        migrations.AlterField(
            model_name="invoicinginformation",
            name="invoice_type",
            field=models.CharField(
                choices=[("SCL", "SCL"), ("CONTRACTOR", "CONTRACTOR")],
                db_index=True,
                help_text='Invoice type: "SCL" or "CONTRACTOR"',
                max_length=50,
            ),
        ),
    ]
