# Generated by Django 6.0.4 on 2026-06-10 11:24

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_gross_certified_scl_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicinginformation',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='invoicinginformation',
            name='gross_billed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross billed amount (>= 0)', max_digits=20),
        ),
        migrations.AddIndex(
            model_name='invoicinginformation',
            index=models.Index(fields=['project_name'], name='inv_project_name_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicinginformation',
            index=models.Index(fields=['invoice_type'], name='inv_invoice_type_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicinginformation',
            index=models.Index(fields=['project_name', 'invoice_type'], name='inv_project_type_idx'),
        ),
    ]
