# Generated by Django 5.2.13 on 2026-07-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_invoicing_multi_contractor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicinginformation',
            options={'ordering': ['project_name', 'invoice_type', 'contractor_name'], 'verbose_name': 'Invoicing Information', 'verbose_name_plural': 'Invoicing Information'},
        ),
    ]
