# Generated by Django 5.2.13 on 2026-07-01 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
        ('invoicing', '0007_alter_invoicinginformation_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoicinginformation',
            name='inv_unique_contractor_name_per_project',
        ),
        migrations.AddField(
            model_name='invoicinginformation',
            name='contractor',
            field=models.ForeignKey(blank=True, help_text='Contractor Master reference (required for CONTRACTOR)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoicing_records', to='contractors.contractor'),
        ),
        migrations.AlterField(
            model_name='invoicinginformation',
            name='contractor_name',
            field=models.CharField(blank=True, db_index=True, help_text='Contractor display name (denormalized from Contractor Master)', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='invoicinginformation',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_type', 'CONTRACTOR')), fields=('project_name', 'contractor'), name='inv_unique_contractor_per_project'),
        ),
    ]
