# Generated by Django 6.0.4 on 2026-05-21 04:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantMachineryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=255)),
                ('report_date', models.DateField(db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plant & Machinery Report',
                'verbose_name_plural': 'Plant & Machinery Reports',
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['project_name', 'report_date'], name='plant_machi_project_459a9b_idx'), models.Index(fields=['-report_date'], name='plant_machi_report__da8d9e_idx')],
                'unique_together': {('project_name', 'report_date')},
            },
        ),
        migrations.CreateModel(
            name='MachineryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('particular', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=0, help_text='Quantity cannot be negative', validators=[django.core.validators.MinValueValidator(0)])),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Under Maintenance', 'Under Maintenance'), ('Not Available', 'Not Available')], default='Working', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machinery_items', to='plant_machinery.plantmachineryreport')),
            ],
            options={
                'verbose_name': 'Machinery Item',
                'verbose_name_plural': 'Machinery Items',
                'ordering': ['sr_no'],
                'indexes': [models.Index(fields=['report', 'sr_no'], name='plant_machi_report__012f21_idx')],
                'unique_together': {('report', 'sr_no')},
            },
        ),
    ]
