# Generated by Django 5.2.13 on 2026-06-02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


DEFAULT_MACHINERY = [
    ("Piling Rig Machine", "Nos", "Piling"),
    ("Piling Rig Tripod", "Nos", "Piling"),
    ("Tower Crane", "Nos", "Lifting"),
    ("Hydra", "Nos", "Lifting"),
    ("JCB", "Nos", "Earthmoving"),
    ("Water Tanker", "Nos", "Logistics"),
    ("Transit Mixer", "Nos", "Concrete"),
]


def seed_machinery_master(apps, schema_editor):
    MachineryMaster = apps.get_model("plant_machinery", "MachineryMaster")
    for name, unit, category in DEFAULT_MACHINERY:
        MachineryMaster.objects.get_or_create(
            name=name,
            defaults={
                "unit": unit,
                "category": category,
                "is_default": True,
            },
        )


def link_existing_items_to_master(apps, schema_editor):
    MachineryMaster = apps.get_model("plant_machinery", "MachineryMaster")
    MachineryItem = apps.get_model("plant_machinery", "MachineryItem")

    for item in MachineryItem.objects.all().order_by("id"):
        name = (getattr(item, "particular", None) or "").strip()
        unit = (getattr(item, "unit", None) or "Nos").strip()
        if not name:
            name = f"Unknown Machinery {item.id}"
        master, _ = MachineryMaster.objects.get_or_create(
            name=name,
            defaults={
                "unit": unit,
                "category": "General",
                "is_default": False,
            },
        )
        item.machinery_master = master
        item.save(update_fields=["machinery_master"])


class Migration(migrations.Migration):

    dependencies = [
        ("plant_machinery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineryMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique machinery name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="Unit of measure (e.g. Nos, Hour)",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Machinery category",
                        max_length=100,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="True for system-seeded default machinery types",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Machinery Master",
                "verbose_name_plural": "Machinery Master",
                "ordering": ["name"],
            },
        ),
        migrations.AddIndex(
            model_name="machinerymaster",
            index=models.Index(fields=["name"], name="pm_master_name_idx"),
        ),
        migrations.AddIndex(
            model_name="machinerymaster",
            index=models.Index(fields=["category"], name="pm_master_category_idx"),
        ),
        migrations.RunPython(seed_machinery_master, migrations.RunPython.noop),
        migrations.AddField(
            model_name="machineryitem",
            name="machinery_master",
            field=models.ForeignKey(
                help_text="Machinery type from global master catalogue",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="log_items",
                to="plant_machinery.machinerymaster",
            ),
        ),
        migrations.RunPython(link_existing_items_to_master, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="machineryitem",
            name="machinery_master",
            field=models.ForeignKey(
                help_text="Machinery type from global master catalogue",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="log_items",
                to="plant_machinery.machinerymaster",
            ),
        ),
        migrations.RemoveField(
            model_name="machineryitem",
            name="particular",
        ),
        migrations.RemoveField(
            model_name="machineryitem",
            name="unit",
        ),
        migrations.AddConstraint(
            model_name="machineryitem",
            constraint=models.UniqueConstraint(
                fields=("report", "machinery_master"),
                name="pm_unique_report_machinery_master",
            ),
        ),
        migrations.AddIndex(
            model_name="machineryitem",
            index=models.Index(
                fields=["machinery_master"],
                name="plant_machi_machiner_idx",
            ),
        ),
    ]
