# Generated by Django 6.0.4 on 2026-06-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant_machinery', '0002_machinery_master'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='machineryitem',
            new_name='plant_machi_machine_30e845_idx',
            old_name='plant_machi_machiner_idx',
        ),
    ]
