# Generated by Django 6.0.4 on 2026-06-01 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=255)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('image_url', models.URLField(max_length=500)),
                ('cloudinary_public_id', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_site_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Progress Image',
                'verbose_name_plural': 'Site Progress Images',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_name', 'year', 'month'], name='site_img_proj_period_idx')],
            },
        ),
    ]
