# Generated by Django 6.0 on 2026-08-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_images', '0002_siteprogressimage_storage_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprogressimage',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Optional display title for the site image', max_length=255, null=True),
        ),
    ]
