# Generated by Django 6.0 on 2026-07-20 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0014_project_merged_into'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('file', models.CharField(help_text='S3 object key under testing/', max_length=700, unique=True)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('mime_type', models.CharField(max_length=120)),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('video', 'Video')], db_index=True, max_length=16)),
                ('test_date', models.DateField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_testing_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testing Document',
                'verbose_name_plural': 'Testing Documents',
                'ordering': ['-test_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestingDocumentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id_snapshot', models.PositiveIntegerField(blank=True, help_text='Preserved document id after soft/hard delete', null=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], db_index=True, max_length=16)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_document_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='testing_documents.testingdocument')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testing_document_audit_logs', to='projects.project')),
            ],
            options={
                'verbose_name': 'Testing Document Audit Log',
                'verbose_name_plural': 'Testing Document Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='testingdocument',
            index=models.Index(fields=['project', 'year', 'month'], name='test_doc_proj_year_month_idx'),
        ),
        migrations.AddIndex(
            model_name='testingdocument',
            index=models.Index(fields=['project', 'document_type', 'is_active'], name='test_doc_proj_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='testingdocument',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='test_doc_uploader_created_idx'),
        ),
    ]
