# Generated by Codex for meeting document management.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0012_project_site_engineer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("meeting_type", models.CharField(choices=[("MOM", "Minutes of Meeting"), ("EDL", "Engineering Decision Log")], db_index=True, max_length=10)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("meeting_date", models.DateField(db_index=True)),
                ("meeting_number", models.CharField(blank=True, db_index=True, max_length=80)),
                ("document_version", models.PositiveIntegerField(db_index=True, default=1)),
                ("file_name", models.CharField(max_length=255)),
                ("original_file_size", models.PositiveBigIntegerField(default=0)),
                ("compressed_file_size", models.PositiveBigIntegerField(default=0)),
                ("compression_percentage", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("content_type", models.CharField(max_length=120)),
                ("s3_key", models.CharField(max_length=700, unique=True)),
                ("s3_url", models.URLField(max_length=1000)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_meeting_documents", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(db_index=True, on_delete=django.db.models.deletion.CASCADE, related_name="meeting_documents", to="projects.project")),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_meeting_documents", to=settings.AUTH_USER_MODEL)),
                ("uploaded_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="uploaded_meeting_documents", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Meeting Document",
                "verbose_name_plural": "Meeting Documents",
                "ordering": ["-meeting_date", "-document_version", "-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="meetingdocument",
            index=models.Index(fields=["project", "meeting_type", "meeting_date"], name="meet_doc_proj_type_date_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingdocument",
            index=models.Index(fields=["project", "meeting_type", "meeting_number"], name="meet_doc_proj_type_no_idx"),
        ),
        migrations.AddIndex(
            model_name="meetingdocument",
            index=models.Index(fields=["project", "is_active", "uploaded_at"], name="meet_doc_active_upload_idx"),
        ),
        migrations.AddConstraint(
            model_name="meetingdocument",
            constraint=models.UniqueConstraint(fields=("project", "meeting_type", "meeting_number", "title", "document_version"), name="meet_doc_unique_number_version"),
        ),
    ]
