# Generated by Django 5.2.13 on 2026-05-27 04:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_index=True, help_text='Unique project name for this correspondence record', max_length=255, unique=True)),
                ('correspondenceReceived', models.PositiveIntegerField(default=0, help_text='Total correspondence items received')),
                ('correspondenceDelivered', models.PositiveIntegerField(default=0, help_text='Total correspondence items delivered (cannot exceed correspondenceReceived)')),
                ('pendingCorrespondence', models.IntegerField(default=0, editable=False, help_text='Auto-calculated: correspondenceReceived - correspondenceDelivered')),
                ('deliveryPercentage', models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: (correspondenceDelivered / correspondenceReceived) * 100')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Correspondence Record',
                'verbose_name_plural': 'Correspondence Records',
                'ordering': ['projectName'],
                'indexes': [models.Index(fields=['projectName'], name='corr_project_name_idx')],
            },
        ),
    ]
