# Generated by Django 5.2.13 on 2026-06-01

from datetime import date

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_correspondence(apps, schema_editor):
    """Move cumulative project totals into first monthly CLIENT record."""
    Correspondence = apps.get_model("correspondence", "Correspondence")
    Project = apps.get_model("projects", "Project")
    today = date.today()

    for record in Correspondence.objects.all():
        project_name = (record.projectName or "").strip()
        if not project_name:
            continue

        project, _ = Project.objects.get_or_create(name=project_name)

        record.month = today.month
        record.year = today.year

        record.project = project
        record.correspondence_type = "CLIENT"
        record.correspondence_received = record.correspondenceReceived or 0
        record.correspondence_delivered = record.correspondenceDelivered or 0
        record.save(
            update_fields=[
                "project",
                "month",
                "year",
                "correspondence_type",
                "correspondence_received",
                "correspondence_delivered",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="correspondence",
            name="corr_project_name_idx",
        ),
        migrations.AddField(
            model_name="correspondence",
            name="project",
            field=models.ForeignKey(
                help_text="Project this correspondence record belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correspondence_records",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="month",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=1, help_text="Month number (1–12)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="correspondence",
            name="year",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=2026, help_text="Year (e.g. 2026)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="correspondence",
            name="correspondence_type",
            field=models.CharField(
                choices=[("CLIENT", "CLIENT"), ("CONTRACTOR", "CONTRACTOR")],
                db_index=True,
                default="CLIENT",
                help_text="CLIENT or CONTRACTOR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="correspondence_received",
            field=models.PositiveIntegerField(
                default=0, help_text="Correspondence items received this month"
            ),
        ),
        migrations.AddField(
            model_name="correspondence",
            name="correspondence_delivered",
            field=models.PositiveIntegerField(
                default=0, help_text="Correspondence items delivered this month"
            ),
        ),
        migrations.RunPython(migrate_legacy_correspondence, migrations.RunPython.noop),
        migrations.RemoveField(model_name="correspondence", name="projectName"),
        migrations.RemoveField(model_name="correspondence", name="correspondenceReceived"),
        migrations.RemoveField(model_name="correspondence", name="correspondenceDelivered"),
        migrations.RemoveField(model_name="correspondence", name="pendingCorrespondence"),
        migrations.RemoveField(model_name="correspondence", name="deliveryPercentage"),
        migrations.AlterField(
            model_name="correspondence",
            name="project",
            field=models.ForeignKey(
                help_text="Project this correspondence record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="correspondence_records",
                to="projects.project",
            ),
        ),
        migrations.RenameModel(
            old_name="Correspondence",
            new_name="CorrespondenceStatus",
        ),
        migrations.AlterModelOptions(
            name="correspondencestatus",
            options={
                "ordering": ["project__name", "year", "month", "correspondence_type"],
                "verbose_name": "Correspondence Status",
                "verbose_name_plural": "Correspondence Status Records",
            },
        ),
        migrations.AlterUniqueTogether(
            name="correspondencestatus",
            unique_together={("project", "month", "year", "correspondence_type")},
        ),
        migrations.AddIndex(
            model_name="correspondencestatus",
            index=models.Index(
                fields=["project", "year", "month", "correspondence_type"],
                name="corr_proj_period_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correspondencestatus",
            index=models.Index(
                fields=["year", "month"],
                name="corr_year_month_idx",
            ),
        ),
    ]
