# Generated by Django 5.2.13 on 2026-06-02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0002_monthly_correspondence_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrespondenceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        db_index=True,
                        help_text="Project name for this document",
                        max_length=255,
                    ),
                ),
                (
                    "party_type",
                    models.CharField(
                        choices=[
                            ("CLIENT", "CLIENT"),
                            ("CONTRACTOR", "CONTRACTOR"),
                        ],
                        db_index=True,
                        help_text="CLIENT or CONTRACTOR",
                        max_length=20,
                    ),
                ),
                (
                    "sr_no",
                    models.PositiveIntegerField(
                        help_text="Serial number within project and party type"
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Document description"),
                ),
                (
                    "received_date",
                    models.DateField(
                        db_index=True,
                        help_text="Date the document was received",
                    ),
                ),
                (
                    "deadline_date",
                    models.DateField(
                        editable=False,
                        help_text="Auto-calculated: received_date + 7 days",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the document was delivered (optional until delivered)",
                        null=True,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Delivered On Time", "Delivered On Time"),
                            ("Delivered Late", "Delivered Late"),
                        ],
                        db_index=True,
                        default="Pending",
                        help_text="Auto-calculated from received, deadline, and delivery dates",
                        max_length=32,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Correspondence Document",
                "verbose_name_plural": "Correspondence Documents",
                "ordering": ["project_name", "party_type", "sr_no"],
            },
        ),
        migrations.AddConstraint(
            model_name="correspondencedocument",
            constraint=models.UniqueConstraint(
                fields=("project_name", "party_type", "sr_no"),
                name="corr_doc_unique_project_party_sr",
            ),
        ),
        migrations.AddIndex(
            model_name="correspondencedocument",
            index=models.Index(fields=["project_name"], name="corr_doc_project_idx"),
        ),
        migrations.AddIndex(
            model_name="correspondencedocument",
            index=models.Index(fields=["party_type"], name="corr_doc_party_idx"),
        ),
        migrations.AddIndex(
            model_name="correspondencedocument",
            index=models.Index(
                fields=["project_name", "party_type"],
                name="corr_doc_proj_party_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correspondencedocument",
            index=models.Index(fields=["received_date"], name="corr_doc_received_idx"),
        ),
        migrations.DeleteModel(
            name="CorrespondenceStatus",
        ),
    ]
