# Generated by Django 5.2.13 on 2026-06-02

from django.db import migrations, models


def backfill_month_year_and_status(apps, schema_editor):
    CorrespondenceDocument = apps.get_model("correspondence", "CorrespondenceDocument")
    status_map = {
        "Pending": "PENDING",
        "Delivered On Time": "DELIVERED_ON_TIME",
        "Delivered Late": "DELIVERED_LATE",
        "PENDING": "PENDING",
        "DELIVERED_ON_TIME": "DELIVERED_ON_TIME",
        "DELIVERED_LATE": "DELIVERED_LATE",
    }
    for doc in CorrespondenceDocument.objects.all().order_by("id"):
        if doc.received_date:
            doc.month = doc.received_date.month
            doc.year = doc.received_date.year
        else:
            doc.month = getattr(doc, "month", None) or 1
            doc.year = getattr(doc, "year", None) or 2026
        doc.delivery_status = status_map.get(
            doc.delivery_status, "PENDING"
        )
        doc.save(update_fields=["month", "year", "delivery_status"])


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0003_correspondence_document_tracking"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="correspondencedocument",
            name="corr_doc_unique_project_party_sr",
        ),
        migrations.RemoveIndex(
            model_name="correspondencedocument",
            name="corr_doc_party_idx",
        ),
        migrations.RemoveIndex(
            model_name="correspondencedocument",
            name="corr_doc_proj_party_idx",
        ),
        migrations.AddField(
            model_name="correspondencedocument",
            name="month",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=1,
                help_text="Month (1–12) this document belongs to",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="correspondencedocument",
            name="year",
            field=models.PositiveSmallIntegerField(
                db_index=True,
                default=2026,
                help_text="Year this document belongs to",
            ),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name="correspondencedocument",
            old_name="party_type",
            new_name="correspondence_type",
        ),
        migrations.AlterModelOptions(
            name="correspondencedocument",
            options={
                "ordering": [
                    "project_name",
                    "year",
                    "month",
                    "correspondence_type",
                    "sr_no",
                ],
                "verbose_name": "Correspondence Document",
                "verbose_name_plural": "Correspondence Documents",
            },
        ),
        migrations.RunPython(
            backfill_month_year_and_status,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="correspondencedocument",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("DELIVERED_ON_TIME", "DELIVERED_ON_TIME"),
                    ("DELIVERED_LATE", "DELIVERED_LATE"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Auto-calculated from dates",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="correspondencedocument",
            constraint=models.UniqueConstraint(
                fields=[
                    "project_name",
                    "month",
                    "year",
                    "correspondence_type",
                    "sr_no",
                ],
                name="corr_doc_unique_project_period_type_sr",
            ),
        ),
        migrations.AddIndex(
            model_name="correspondencedocument",
            index=models.Index(
                fields=["project_name", "year", "month", "correspondence_type"],
                name="corr_doc_proj_period_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="correspondencedocument",
            index=models.Index(
                fields=["year", "month"],
                name="corr_doc_year_month_idx",
            ),
        ),
    ]
