# Generated by Django 5.2.13 on 2026-06-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0004_monthly_correspondence_type_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="correspondencedocument",
            old_name="delivery_date",
            new_name="delivered_date",
        ),
        migrations.RenameField(
            model_name="correspondencedocument",
            old_name="delivery_status",
            new_name="delivered_status",
        ),
    ]
