# Generated by Django 6.0.4 on 2026-06-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0006_flow_direction_scl_outbound'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='correspondencedocument',
            name='corr_doc_received_idx',
        ),
        migrations.AlterField(
            model_name='correspondencedocument',
            name='correspondence_type',
            field=models.CharField(choices=[('CLIENT', 'CLIENT'), ('CONTRACTOR', 'CONTRACTOR'), ('OTHER_AGENCY', 'OTHER_AGENCY')], db_index=True, help_text='CLIENT or CONTRACTOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='correspondencedocument',
            name='delivered_date',
            field=models.DateField(blank=True, help_text='Date delivered (null while pending)', null=True),
        ),
        migrations.AlterField(
            model_name='correspondencedocument',
            name='delivered_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DELIVERED_ON_TIME', 'DELIVERED_ON_TIME'), ('DELIVERED_LATE', 'DELIVERED_LATE')], db_index=True, default='PENDING', help_text='Auto-calculated: PENDING, DELIVERED_ON_TIME, DELIVERED_LATE', max_length=32),
        ),
        migrations.AlterField(
            model_name='correspondencedocument',
            name='project_name',
            field=models.CharField(db_index=True, help_text='Project name', max_length=255),
        ),
        migrations.AlterField(
            model_name='correspondencedocument',
            name='sr_no',
            field=models.PositiveIntegerField(help_text='Serial number within project, month, year, and type'),
        ),
    ]
