# Generated by Django 5.2.13 on 2026-06-17 09:41

from django.db import migrations, models


def backfill_delivered_counts(apps, schema_editor):
    Summary = apps.get_model("correspondence", "SCLDeliveredCorrespondenceSummary")
    for summary in Summary.objects.all():
        summary.client_delivered = summary.client or 0
        summary.contractor_delivered = summary.contractor or 0
        summary.other_agency_delivered = summary.other_agency or 0
        summary.save(
            update_fields=[
                "client_delivered",
                "contractor_delivered",
                "other_agency_delivered",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0008_scldeliveredcorrespondencesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='scldeliveredcorrespondencesummary',
            name='client_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scldeliveredcorrespondencesummary',
            name='client_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scldeliveredcorrespondencesummary',
            name='contractor_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scldeliveredcorrespondencesummary',
            name='contractor_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scldeliveredcorrespondencesummary',
            name='other_agency_delivered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scldeliveredcorrespondencesummary',
            name='other_agency_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_delivered_counts, migrations.RunPython.noop),
    ]
