# Generated by Django 5.2.13 on 2026-07-01 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0009_scldeliveredcorrespondencesummary_client_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scldeliveredcorrespondencesummary',
            name='client_record',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scldeliveredcorrespondencesummary',
            name='contractor_record',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scldeliveredcorrespondencesummary',
            name='other_agency_record',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InboundCorrespondenceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=255)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('view', models.CharField(choices=[('monthly', 'Monthly'), ('cumulative', 'Cumulative')], db_index=True, default='monthly', max_length=20)),
                ('client_received', models.PositiveIntegerField(default=0)),
                ('client_delivered', models.PositiveIntegerField(default=0)),
                ('client_record', models.PositiveIntegerField(default=0)),
                ('contractor_received', models.PositiveIntegerField(default=0)),
                ('contractor_delivered', models.PositiveIntegerField(default=0)),
                ('contractor_record', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inbound Correspondence Summary',
                'verbose_name_plural': 'Inbound Correspondence Summaries',
                'ordering': ['-year', '-month', 'project_name'],
                'constraints': [models.UniqueConstraint(fields=('project_name', 'year', 'month', 'view'), name='inbound_corr_unique_project_period_view')],
            },
        ),
    ]
