# Generated by Django 6.0.4 on 2026-07-09 05:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0011_correspondencedocument_correspondence_category'),
        ('projects', '0012_project_site_engineer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenceDocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(blank=True, max_length=120)),
                ('document_version', models.PositiveIntegerField(db_index=True, default=1)),
                ('version_group', models.CharField(db_index=True, max_length=255)),
                ('original_file_size', models.PositiveBigIntegerField(default=0)),
                ('compressed_file_size', models.PositiveBigIntegerField(default=0)),
                ('compression_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('content_type', models.CharField(max_length=120)),
                ('s3_key', models.CharField(max_length=700, unique=True)),
                ('s3_url', models.URLField(max_length=1000)),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('correspondence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='correspondence.correspondencedocument')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_correspondence_attachments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_attachments', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_correspondence_attachments', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_correspondence_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Correspondence Document Attachment',
                'verbose_name_plural': 'Correspondence Document Attachments',
                'ordering': ['-uploaded_at', '-document_version'],
                'indexes': [models.Index(fields=['correspondence', 'is_active', 'uploaded_at'], name='corr_att_corr_active_idx'), models.Index(fields=['correspondence', 'version_group', 'document_version'], name='corr_att_version_idx')],
            },
        ),
    ]
