# Generated by Django 6.0 on 2026-07-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0012_correspondencedocumentattachment'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='correspondencedocument',
            name='corr_doc_project_idx',
        ),
        migrations.AddIndex(
            model_name='correspondencedocument',
            index=models.Index(fields=['project_name', 'flow_direction', 'year', 'month'], name='corr_proj_flow_period_idx'),
        ),
        migrations.AddIndex(
            model_name='correspondencedocument',
            index=models.Index(fields=['project_name', 'delivered_status', 'correspondence_category'], name='corr_proj_status_cat_idx'),
        ),
    ]
