# Generated by Django 6.0 on 2026-08-17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("correspondence", "0013_optimize_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrespondenceComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "commented_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correspondence_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "correspondence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="correspondence.correspondencedocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "Correspondence Comment",
                "verbose_name_plural": "Correspondence Comments",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["correspondence", "is_active", "created_at"],
                        name="corr_comment_active_time_idx",
                    ),
                ],
            },
        ),
    ]
