# Generated by Django 5.2.13 on 2026-05-21 05:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManpowerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_index=True, max_length=255)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('monthly_planned_manpower', models.IntegerField(help_text='Planned manpower for the month (cannot be negative)', validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_manpower', models.IntegerField(help_text='Actual manpower deployed (cannot be negative)', validators=[django.core.validators.MinValueValidator(0)])),
                ('difference', models.IntegerField(editable=False, help_text='Auto-calculated: actual_manpower - monthly_planned_manpower')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manpower Record',
                'verbose_name_plural': 'Manpower Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_name', 'year', 'month'], name='manpower_ma_project_e32867_idx'), models.Index(fields=['-created_at'], name='manpower_ma_created_515746_idx')],
                'unique_together': {('project_name', 'month', 'year')},
            },
        ),
    ]
