# Generated by Django 5.2.13 on 2026-05-27 04:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(db_index=True, help_text='Unique project name for this drawing record', max_length=255, unique=True)),
                ('totalSubmitted', models.PositiveIntegerField(default=0, help_text='Total number of drawings submitted')),
                ('totalApproved', models.PositiveIntegerField(default=0, help_text='Total number of drawings approved (cannot exceed totalSubmitted)')),
                ('variance', models.IntegerField(default=0, editable=False, help_text='Auto-calculated: totalSubmitted - totalApproved')),
                ('approvalPercentage', models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: (totalApproved / totalSubmitted) * 100')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Drawing',
                'verbose_name_plural': 'Drawings',
                'ordering': ['projectName'],
                'indexes': [models.Index(fields=['projectName'], name='drawing_project_name_idx')],
            },
        ),
    ]
