# Generated by Django 5.2.13 on 2026-06-01

from datetime import date

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_drawings(apps, schema_editor):
    """Move cumulative project totals into first monthly record."""
    Drawing = apps.get_model("drawings", "Drawing")
    Project = apps.get_model("projects", "Project")
    today = date.today()

    for record in Drawing.objects.all():
        project_name = (record.projectName or "").strip()
        if not project_name:
            continue

        project, _ = Project.objects.get_or_create(name=project_name)

        if record.created_at:
            record.month = record.created_at.month
            record.year = record.created_at.year
        else:
            record.month = today.month
            record.year = today.year

        record.project = project
        record.submitted_drawings = record.totalSubmitted or 0
        record.approved_drawings = record.totalApproved or 0
        record.save(
            update_fields=[
                "project",
                "month",
                "year",
                "submitted_drawings",
                "approved_drawings",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("drawings", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="drawing",
            name="project",
            field=models.ForeignKey(
                help_text="Project this drawing summary belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawing_summaries",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="month",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=1, help_text="Month number (1–12)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drawing",
            name="year",
            field=models.PositiveSmallIntegerField(
                db_index=True, default=2026, help_text="Year (e.g. 2026)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="drawing",
            name="submitted_drawings",
            field=models.PositiveIntegerField(
                default=0, help_text="Drawings submitted this month"
            ),
        ),
        migrations.AddField(
            model_name="drawing",
            name="approved_drawings",
            field=models.PositiveIntegerField(
                default=0, help_text="Drawings approved this month"
            ),
        ),
        migrations.RunPython(migrate_legacy_drawings, migrations.RunPython.noop),
        migrations.RemoveField(model_name="drawing", name="projectName"),
        migrations.RemoveField(model_name="drawing", name="totalSubmitted"),
        migrations.RemoveField(model_name="drawing", name="totalApproved"),
        migrations.RemoveField(model_name="drawing", name="variance"),
        migrations.RemoveField(model_name="drawing", name="approvalPercentage"),
        migrations.AlterField(
            model_name="drawing",
            name="project",
            field=models.ForeignKey(
                help_text="Project this drawing summary belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawing_summaries",
                to="projects.project",
            ),
        ),
        migrations.RenameModel(
            old_name="Drawing",
            new_name="DrawingSummary",
        ),
        migrations.AlterModelOptions(
            name="drawingsummary",
            options={
                "ordering": ["project__name", "year", "month"],
                "verbose_name": "Drawing Summary",
                "verbose_name_plural": "Drawing Summaries",
            },
        ),
        migrations.AlterUniqueTogether(
            name="drawingsummary",
            unique_together={("project", "month", "year")},
        ),
        migrations.RemoveIndex(
            model_name="drawingsummary",
            name="drawing_project_name_idx",
        ),
        migrations.AddIndex(
            model_name="drawingsummary",
            index=models.Index(
                fields=["project", "year", "month"],
                name="drawing_proj_year_month_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="drawingsummary",
            index=models.Index(
                fields=["year", "month"],
                name="drawing_year_month_idx",
            ),
        ),
    ]
