# Generated by Django 6.0.4 on 2026-06-10 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_monthly_drawing_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawingsummary',
            name='approved_drawings',
            field=models.PositiveIntegerField(default=0, help_text='Drawings approved this month (cannot exceed submitted_drawings)'),
        ),
        migrations.AlterField(
            model_name='drawingsummary',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='drawingsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
