# Generated by Django 6.0.4 on 2026-06-12 08:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0003_alter_drawingsummary_approved_drawings_and_more'),
        ('projects', '0011_projectlogentry_bottleneck_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingRegisterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.PositiveIntegerField(help_text='Serial number within the project register')),
                ('drawing_name', models.CharField(help_text='Design and drawing title', max_length=500)),
                ('contractor_name', models.CharField(blank=True, db_index=True, default='', help_text='Contractor associated with this drawing', max_length=255)),
                ('revision', models.PositiveSmallIntegerField(default=1, help_text='Drawing revision number')),
                ('remarks', models.CharField(blank=True, default='', help_text='Current status / remarks (e.g. Approved, Pending)', max_length=255)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('consultant_comments_date', models.DateField(blank=True, null=True)),
                ('resubmitted_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawing_register_items', to='projects.project')),
            ],
            options={
                'verbose_name': 'Drawing Register Item',
                'verbose_name_plural': 'Drawing Register Items',
                'ordering': ['project__name', 'sr_no', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='DrawingWorkflowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submission by Contractor'), ('CONSULTANT_COMMENTED', 'Comments/Approval by Consultant'), ('RESUBMITTED', 'Re-submission by Contractor'), ('APPROVED', 'Approved by Consultant')], db_index=True, max_length=32)),
                ('event_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_events', to='drawings.drawingregisteritem')),
            ],
            options={
                'verbose_name': 'Drawing Workflow Event',
                'verbose_name_plural': 'Drawing Workflow Events',
                'ordering': ['event_date', 'created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='drawingregisteritem',
            index=models.Index(fields=['project', 'sr_no'], name='draw_reg_proj_sr_idx'),
        ),
        migrations.AddIndex(
            model_name='drawingregisteritem',
            index=models.Index(fields=['project', 'contractor_name'], name='draw_reg_proj_contr_idx'),
        ),
        migrations.AddConstraint(
            model_name='drawingregisteritem',
            constraint=models.UniqueConstraint(fields=('project', 'sr_no', 'revision'), name='drawing_register_unique_sr_revision'),
        ),
        migrations.AddIndex(
            model_name='drawingworkflowevent',
            index=models.Index(fields=['drawing', 'action', 'event_date'], name='draw_wf_action_dt_idx'),
        ),
    ]
