# Generated by Django 6.0 on 2026-08-12 08:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0004_drawing_register'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveSmallIntegerField(help_text='Drawing revision at upload time (immutable snapshot)')),
                ('original_filename', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=512, unique=True)),
                ('file_url', models.URLField(max_length=1024)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('file_extension', models.CharField(blank=True, default='', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drawing_register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='drawings.drawingregisteritem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drawing_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drawing File',
                'verbose_name_plural': 'Drawing Files',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['drawing_register', 'revision', 'is_active'], name='draw_file_reg_rev_idx')],
            },
        ),
    ]
