"""
S3 helpers for generated MPR PDF/Excel files.

Key layout (prefix from settings.MPR_S3_PREFIX, default ``mpr``):
  mpr/{project_id}/{year}/{month}/mpr_{project_id}_{year}_{month}_v{version}.pdf
  mpr/{project_id}/{year}/{month}/mpr_{project_id}_{year}_{month}_v{version}.xlsx
"""

from __future__ import annotations

import logging
from io import BytesIO
from pathlib import Path

from django.conf import settings
from django.core.files.storage import default_storage

from core.s3_config import (
    DEFAULT_OBJECT_CACHE_CONTROL,
    get_s3_client,
    is_boto3_available,
    is_s3_configured,
    s3_public_url,
)

logger = logging.getLogger(__name__)

PRESIGNED_EXPIRY_SECONDS = 15 * 60


def mpr_root() -> str:
    return str(getattr(settings, "MPR_S3_PREFIX", "mpr")).strip("/") or "mpr"


def check_s3_ready() -> tuple[bool, str | None]:
    if not is_boto3_available():
        return False, "boto3 is not installed"
    if not is_s3_configured():
        return False, "AWS S3 configuration missing"
    return True, None


def build_object_key(
    *,
    project_id: int,
    year: int,
    month: int,
    version: int,
    ext: str,
) -> str:
    ext = ext if ext.startswith(".") else f".{ext}"
    filename = f"mpr_{int(project_id)}_{int(year)}_{int(month):02d}_v{int(version)}{ext}"
    return f"{mpr_root()}/{int(project_id)}/{int(year)}/{int(month):02d}/{filename}"


def s3_object_url(s3_key: str) -> str:
    return s3_public_url(s3_key)


def upload_mpr_bytes(
    *,
    content: bytes,
    project_id: int,
    year: int,
    month: int,
    version: int,
    ext: str,
    content_type: str,
) -> dict:
    """
    Upload generated bytes to S3 (or local media fallback when S3 unavailable).

    Returns: {s3_key, url, size, storage}
    """
    if not content:
        raise ValueError("Generated file content is empty.")

    s3_key = build_object_key(
        project_id=project_id,
        year=year,
        month=month,
        version=version,
        ext=ext,
    )
    size = len(content)
    ready, _err = check_s3_ready()

    if ready:
        client = get_s3_client()
        bucket = settings.AWS_STORAGE_BUCKET_NAME
        logger.info(
            "MPR S3 upload start project_id=%s key=%s size=%s",
            project_id,
            s3_key,
            size,
        )
        client.upload_fileobj(
            BytesIO(content),
            bucket,
            s3_key,
            ExtraArgs={
                "ContentType": content_type,
                "CacheControl": DEFAULT_OBJECT_CACHE_CONTROL,
                "Metadata": {
                    "project-id": str(project_id),
                    "report-year": str(year),
                    "report-month": str(month),
                    "version": str(version),
                },
            },
        )
        url = s3_object_url(s3_key)
        logger.info("MPR S3 upload success key=%s", s3_key)
        return {"s3_key": s3_key, "url": url, "size": size, "storage": "s3"}

    # Local fallback for tests / environments without AWS
    path = default_storage.save(s3_key, BytesIO(content))
    try:
        url = default_storage.url(path)
    except Exception:
        url = f"/media/{path}"
    logger.warning("MPR stored locally (S3 unavailable) path=%s", path)
    return {"s3_key": path, "url": url, "size": size, "storage": "local"}


def presigned_download_url(s3_key: str, *, filename: str | None = None) -> str | None:
    """Return a short-lived GET URL for private objects; public URL fallback."""
    if not s3_key:
        return None
    ready, _ = check_s3_ready()
    if not ready:
        try:
            return default_storage.url(s3_key)
        except Exception:
            return None
    try:
        client = get_s3_client()
        params = {
            "Bucket": settings.AWS_STORAGE_BUCKET_NAME,
            "Key": s3_key,
        }
        if filename:
            params["ResponseContentDisposition"] = (
                f'attachment; filename="{Path(filename).name}"'
            )
        return client.generate_presigned_url(
            "get_object",
            Params=params,
            ExpiresIn=PRESIGNED_EXPIRY_SECONDS,
        )
    except Exception:
        logger.exception("MPR presign failed key=%s", s3_key)
        try:
            return s3_object_url(s3_key)
        except Exception:
            return None
