# Generated by Django 5.2.13 on 2026-09-18 04:49

import organization_registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('office_address', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('pin', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=30)),
                ('official_email', models.EmailField(max_length=254)),
                ('admin_name', models.CharField(max_length=255)),
                ('admin_email', models.EmailField(max_length=254)),
                ('logo', models.FileField(upload_to=organization_registrations.models.organization_logo_upload_to)),
                ('logo_original_name', models.CharField(blank=True, default='', max_length=255)),
                ('logo_s3_key', models.CharField(blank=True, default='', max_length=700)),
                ('logo_s3_url', models.URLField(blank=True, default='', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Organization Registration',
                'verbose_name_plural': 'Organization Registrations',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
