# Generated by Django 5.2.13 on 2026-09-21 07:02

import organization_registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationregistration',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=organization_registrations.models.organization_logo_upload_to),
        ),
    ]
