# Generated by Django 6.0 on 2026-03-17 10:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='Project name for this performance record', max_length=255)),
                ('contract_value', models.DecimalField(decimal_places=2, help_text='Base contract value for percentage calculations', max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('earned_value', models.DecimalField(decimal_places=2, default=0, help_text='Value of work completed (Earned Value)', max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_billed', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually billed', max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('earned_value_percentage', models.FloatField(default=0.0, help_text='Earned Value percentage (calculated: earned_value / contract_value * 100)')),
                ('actual_billed_percentage', models.FloatField(default=0.0, help_text='Actual Billed percentage (calculated: actual_billed / contract_value * 100)')),
                ('variance', models.DecimalField(decimal_places=2, default=0, help_text='Variance amount (calculated: earned_value - actual_billed)', max_digits=18)),
                ('variance_percentage', models.FloatField(default=0.0, help_text='Variance percentage (calculated: variance / contract_value * 100)')),
                ('performance_status', models.CharField(choices=[('red', 'Red (< 90%)'), ('yellow', 'Yellow (90% - 99%)'), ('green', 'Green (>= 100%)')], default='red', help_text='Performance status based on earned_value_percentage thresholds', max_length=20)),
                ('created_by', models.CharField(help_text='User who created this record', max_length=255)),
                ('updated_by', models.CharField(blank=True, help_text='User who last updated this record', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contract Performance',
                'verbose_name_plural': 'Contract Performance',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project_name', '-created_at'], name='contract_pe_project_bb13ca_idx'), models.Index(fields=['performance_status', '-created_at'], name='contract_pe_perform_cd5942_idx')],
            },
        ),
    ]
