# Generated by Django 6.0.2 on 2026-03-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractperformance',
            name='variance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Variance amount (calculated: earned_value - actual_billed). Can be negative if actual_billed > earned_value.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='contractperformance',
            name='variance_percentage',
            field=models.FloatField(default=0.0, help_text='Variance percentage (calculated: variance / contract_value * 100). Can be negative if actual_billed > earned_value.'),
        ),
    ]
