# Generated by Django 6.0.4 on 2026-06-10 11:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_performance', '0004_refactor_billed_receipt_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractperformance',
            name='performancePercentage',
            field=models.FloatField(default=0.0, editable=False, help_text='Auto-calculated: (actualReceiptValue / billedValue) * 100. Represents collection performance as a percentage. 0.0 when billedValue = 0.'),
        ),
        migrations.AlterField(
            model_name='contractperformance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update timestamp'),
        ),
        migrations.AlterField(
            model_name='contractperformance',
            name='variance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Auto-calculated: billedValue - actualReceiptValue. Positive = under-collected. Negative = over-collected.', max_digits=20),
        ),
    ]
