# Generated by Django 6.0 on 2026-07-23 07:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_performance', '0005_remove_contractperformance_contract_pe_project_bb13ca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractperformance',
            name='cosExtraItem',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='COS / Extra Item value (>= 0). Manually editable; not used in KPI auto-calcs.', max_digits=20),
        ),
    ]
