# Generated by Django 6.0 on 2026-07-31 04:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_performance', '0006_add_cos_extra_item'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contractperformance',
            name='cp_project_name_idx',
        ),
        migrations.AlterField(
            model_name='contractperformance',
            name='cosExtraItem',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Legacy unused column; COS is on ContractValue.cos', max_digits=20),
        ),
    ]
