# Generated by Django 6.0 on 2026-03-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogressreport',
            name='billing_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
