# Generated by Django 6.0 on 2026-03-04 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_dailyprogressreport_billing_status'),
        ('projects', '0004_project_coordinators_project_pmc_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprogressreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dprs', to='projects.project'),
        ),
    ]
