# Generated by Django 6.0 on 2026-08-11 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0018_billing_status_db_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MPRReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.PositiveSmallIntegerField(help_text='Month number 1–12')),
                ('report_year', models.PositiveSmallIntegerField(help_text='Four-digit year')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('snapshot_json', models.JSONField(blank=True, help_text='Immutable MPR payload used for PDF/Excel generation', null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_mpr_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpr_reports', to='projects.project')),
            ],
            options={
                'verbose_name': 'MPR Report',
                'verbose_name_plural': 'MPR Reports',
                'ordering': ['-report_year', '-report_month', '-id'],
                'indexes': [models.Index(fields=['project', 'report_year', 'report_month'], name='mpr_proj_period_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'report_year', 'report_month'), name='mpr_unique_project_year_month')],
            },
        ),
    ]
