# Generated by Django 6.0 on 2026-08-11 04:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpr', '0001_initial_mpr_report'),
        ('projects', '0018_billing_status_db_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mprreport',
            options={'ordering': ['-report_year', '-report_month', '-version', '-id'], 'verbose_name': 'MPR Report', 'verbose_name_plural': 'MPR Reports'},
        ),
        migrations.RemoveConstraint(
            model_name='mprreport',
            name='mpr_unique_project_year_month',
        ),
        migrations.AddField(
            model_name='mprreport',
            name='error_message',
            field=models.CharField(blank=True, default='', help_text='Safe client-facing failure summary (no stack traces)', max_length=500),
        ),
        migrations.AddField(
            model_name='mprreport',
            name='excel_key',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
        migrations.AddField(
            model_name='mprreport',
            name='excel_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mprreport',
            name='generation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mprreport',
            name='is_latest',
            field=models.BooleanField(db_index=True, default=True, help_text='True for the newest version of this project+month'),
        ),
        migrations.AddField(
            model_name='mprreport',
            name='pdf_key',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
        migrations.AddField(
            model_name='mprreport',
            name='pdf_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='mprreport',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Monotonic version per project+month (regenerate creates a new version)'),
        ),
        migrations.AlterField(
            model_name='mprreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('mpr', 'MPRReport').objects.filter(status='generated').update(status='completed'),
            reverse_code=lambda apps, schema_editor: apps.get_model('mpr', 'MPRReport').objects.filter(status='completed').update(status='generated'),
        ),
        migrations.AddIndex(
            model_name='mprreport',
            index=models.Index(fields=['project', 'is_latest', '-report_year', '-report_month'], name='mpr_proj_latest_idx'),
        ),
        migrations.AddConstraint(
            model_name='mprreport',
            constraint=models.UniqueConstraint(fields=('project', 'report_year', 'report_month', 'version'), name='mpr_unique_project_year_month_version'),
        ),
    ]
