# Generated by Django 6.0 on 2026-07-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_performance', '0003_populate_project_field'),
        ('projects', '0015_optimize_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budgetcostperformance',
            index=models.Index(fields=['project', '-created_at'], name='bcp_project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetcostperformance',
            index=models.Index(fields=['project_name', '-created_at'], name='bcp_project_name_created_idx'),
        ),
    ]
